CREATE TABLE ORGANIZACIONA_JEDINICA
(
    SIFRA_JEDINICE             CHAR(18)      NOT NULL,
    SIFRA_NADREDJENE_JEDINICE  CHAR(18),
    NAZIV_JEDINICE             VARCHAR(60)   NOT NULL,
    TIP_JEDINICE               VARCHAR(30),
    OPIS_DELATNOSTI            VARCHAR(255),
    DATUM_OSNIVANJA            DATE,
    BROJ_ZAPOSLENIH            INTEGER,
    CONSTRAINT PK_ORGANIZACIONA_JEDINICA PRIMARY KEY (SIFRA_JEDINICE)
);

CREATE TABLE ZAPOSLENI
(
    SIFRA_ZAPOSLENOG   CHAR(18)       NOT NULL,
    SIFRA_JEDINICE     CHAR(18)       NOT NULL,
    JMBG               CHAR(13)       NOT NULL,
    IME                VARCHAR(30)    NOT NULL,
    PREZIME            VARCHAR(30)    NOT NULL,
    RADNO_MESTO        VARCHAR(60),
    DATUM_ZAPOSLENJA   DATE,
    OSNOVNA_ZARADA     DECIMAL(12,2),
    STATUS_ZAPOSLENJA  VARCHAR(20),
    CONSTRAINT PK_ZAPOSLENI PRIMARY KEY (SIFRA_ZAPOSLENOG)
);

CREATE TABLE UREDNIK
(
    SIFRA_ZAPOSLENOG  CHAR(18)     NOT NULL,
    NIVO_OVLASCENJA   VARCHAR(30),
    REDAKCIJA         VARCHAR(60),
    CONSTRAINT PK_UREDNIK PRIMARY KEY (SIFRA_ZAPOSLENOG)
);

CREATE TABLE NOVINAR_REPORTER
(
    SIFRA_ZAPOSLENOG         CHAR(18)     NOT NULL,
    OBLAST_IZVESTAVANJA      VARCHAR(60),
    BROJ_NOVINARSKE_LEGITIM  VARCHAR(20),
    CONSTRAINT PK_NOVINAR_REPORTER PRIMARY KEY (SIFRA_ZAPOSLENOG)
);

CREATE TABLE TEHNICKO_OSOBLJE
(
    SIFRA_ZAPOSLENOG  CHAR(18)     NOT NULL,
    SPECIJALIZACIJA   VARCHAR(60),
    TIP_EKIPE         VARCHAR(30),
    CONSTRAINT PK_TEHNICKO_OSOBLJE PRIMARY KEY (SIFRA_ZAPOSLENOG)
);

CREATE TABLE REFERENT
(
    SIFRA_ZAPOSLENOG  CHAR(18)     NOT NULL,
    TIP_REFERENTA     VARCHAR(30),
    NIVO_OVLASCENJA   VARCHAR(30),
    CONSTRAINT PK_REFERENT PRIMARY KEY (SIFRA_ZAPOSLENOG)
);

CREATE TABLE SERVISERI
(
    SIFRA_ZAPOSLENOG  CHAR(18)     NOT NULL,
    LICENCA           VARCHAR(60),
    CONSTRAINT PK_SERVISERI PRIMARY KEY (SIFRA_ZAPOSLENOG)
);

CREATE TABLE OPREMA
(
    INVENTARSKI_BROJ  CHAR(18)       NOT NULL,
    NAZIV_OPREME      VARCHAR(60)    NOT NULL,
    MODEL_OPREME      VARCHAR(60),
    PROIZVODJAC       VARCHAR(60),
    STATUS_OPREME     VARCHAR(20),
    DATUM_NABAVKE     DATE,
    GARANCIJA_DO      DATE,
    NABAVNA_VREDNOST  DECIMAL(12,2),
    CONSTRAINT PK_OPREMA PRIMARY KEY (INVENTARSKI_BROJ)
);

CREATE TABLE SNIMATELJSKA_OPREMA
(
    INVENTARSKI_BROJ           CHAR(18)     NOT NULL,
    TIP_MEMORIJSKOG_SKLADISTA  VARCHAR(30),
    REZOLUCIJA                 VARCHAR(20),
    TIP_KAMERE                 VARCHAR(30),
    CONSTRAINT PK_SNIMATELJSKA_OPREMA PRIMARY KEY (INVENTARSKI_BROJ)
);

CREATE TABLE STUDIJSKA_I_EMISIONA_OPREMA
(
    INVENTARSKI_BROJ    CHAR(18)     NOT NULL,
    LOKACIJA_U_STUDIJU  VARCHAR(60),
    CONSTRAINT PK_STUDIJSKA_I_EMISIONA_OPREMA PRIMARY KEY (INVENTARSKI_BROJ)
);

CREATE TABLE AUDIO_OPREMA
(
    INVENTARSKI_BROJ  CHAR(18)     NOT NULL,
    TIP               VARCHAR(30),
    FREKVENCIJA       VARCHAR(20),
    CONSTRAINT PK_AUDIO_OPREMA PRIMARY KEY (INVENTARSKI_BROJ)
);

CREATE TABLE SVETLOSNA_OPREMA
(
    INVENTARSKI_BROJ  CHAR(18)     NOT NULL,
    SNAGA             VARCHAR(20),
    TIP_SVETLOSTI     VARCHAR(30),
    CONSTRAINT PK_SVETLOSNA_OPREMA PRIMARY KEY (INVENTARSKI_BROJ)
);

CREATE TABLE ZADUZENJE_OPREME
(
    SIFRA_ZAPOSLENOG     CHAR(18)      NOT NULL,
    INVENTARSKI_BROJ     CHAR(18)      NOT NULL,
    DATUM_ZADUZENJA      DATE          NOT NULL,
    DATUM_RAZDUZENJA     DATE,
    STANJE_PRI_VRACANJU  VARCHAR(255),
    CONSTRAINT PK_ZADUZENJE_OPREME PRIMARY KEY (SIFRA_ZAPOSLENOG, INVENTARSKI_BROJ, DATUM_ZADUZENJA)
);

CREATE TABLE SERVISIRANJE_OPREME
(
    SIFRA_ZAPOSLENOG  CHAR(18)       NOT NULL,
    INVENTARSKI_BROJ  CHAR(18)       NOT NULL,
    DATUM_SERVISA     DATE           NOT NULL,
    OPIS_RADOVA       VARCHAR(255),
    TROSAK            DECIMAL(12,2),
    CONSTRAINT PK_SERVISIRANJE_OPREME PRIMARY KEY (SIFRA_ZAPOSLENOG, INVENTARSKI_BROJ, DATUM_SERVISA)
);

CREATE TABLE PROJEKAT_PRODUKCIJE
(
    SIFRA_PROJEKTA    CHAR(18)       NOT NULL,
    SIFRA_UREDNIKA    CHAR(18)       NOT NULL,
    SIFRA_EMISIJE     CHAR(18),
    NAZIV_PROJEKTA    VARCHAR(60)    NOT NULL,
    DATUM_POCETKA     DATE,
    DATUM_ZAVRSETKA   DATE,
    ODOBREN_BUDZET    DECIMAL(12,2),
    STATUS_PROJEKTA   VARCHAR(20),
    VRSTA_PRODUKCIJE  VARCHAR(30),
    OPIS_PROJEKTA     VARCHAR(255),
    CONSTRAINT PK_PROJEKAT_PRODUKCIJE PRIMARY KEY (SIFRA_PROJEKTA)
);

CREATE TABLE AKTIVNOST_PRODUKCIJE
(
    SIFRA_PROJEKTA     CHAR(18)     NOT NULL,
    RB_AKTIVNOSTI      INTEGER      NOT NULL,
    NAZIV_AKTIVNOSTI   VARCHAR(60)  NOT NULL,
    DATUM_OD           DATE,
    DATUM_DO           DATE,
    VRSTA_AKTIVNOSTI   VARCHAR(30),
    LOKACIJA_SNIMANJA  VARCHAR(60),
    STATUS_AKTIVNOSTI  VARCHAR(20),
    CONSTRAINT PK_AKTIVNOST_PRODUKCIJE PRIMARY KEY (SIFRA_PROJEKTA, RB_AKTIVNOSTI)
);

CREATE TABLE TROSAK_PRODUKCIJE
(
    SIFRA_PROJEKTA  CHAR(18)       NOT NULL,
    RB_AKTIVNOSTI   INTEGER        NOT NULL,
    RB_TROSKA       INTEGER        NOT NULL,
    BROJ_FAKTURE    CHAR(18),
    VRSTA_TROSKA    VARCHAR(30),
    IZNOS           DECIMAL(12,2)  NOT NULL,
    DATUM_NASTANKA  DATE,
    OPIS_TROSKA     VARCHAR(255),
    CONSTRAINT PK_TROSAK_PRODUKCIJE PRIMARY KEY (SIFRA_PROJEKTA, RB_AKTIVNOSTI, RB_TROSKA)
);

CREATE TABLE ANGAZOVANJE_NA_AKTIVNOSTI
(
    SIFRA_PROJEKTA         CHAR(18)     NOT NULL,
    RB_AKTIVNOSTI          INTEGER      NOT NULL,
    SIFRA_ZAPOSLENOG       CHAR(18)     NOT NULL,
    ULOGA_NA_SNIMANJU      VARCHAR(60),
    DATUM_OD               DATE,
    DATUM_DO               DATE,
    BROJ_ANGAZOVANIH_SATI  INTEGER,
    CONSTRAINT PK_ANGAZOVANJE_NA_AKTIVNOSTI PRIMARY KEY (SIFRA_PROJEKTA, RB_AKTIVNOSTI, SIFRA_ZAPOSLENOG)
);

CREATE TABLE REZERVACIJA_OPREME
(
    SIFRA_PROJEKTA      CHAR(18)  NOT NULL,
    RB_AKTIVNOSTI       INTEGER   NOT NULL,
    INVENTARSKI_BROJ    CHAR(18)  NOT NULL,
    DATUM_REZERVACIJE   DATE,
    TRAJANJE_ZADUZENJA  INTEGER,
    CONSTRAINT PK_REZERVACIJA_OPREME PRIMARY KEY (SIFRA_PROJEKTA, RB_AKTIVNOSTI, INVENTARSKI_BROJ)
);

CREATE TABLE SIROVI_SNIMAK
(
    SIFRA_SNIMKA     CHAR(18)     NOT NULL,
    SIFRA_PROJEKTA   CHAR(18)     NOT NULL,
    RB_AKTIVNOSTI    INTEGER      NOT NULL,
    DATUM_SNIMANJA   DATE,
    TRAJANJE         INTEGER,
    FORMAT_SNIMKA    VARCHAR(30),
    LOKACIJA_SNIMKA  VARCHAR(60),
    OCENA_KVALITETA  VARCHAR(20),
    CONSTRAINT PK_SIROVI_SNIMAK PRIMARY KEY (SIFRA_SNIMKA)
);

CREATE TABLE GRAFICKI_I_MUZICKI_ELEMENT
(
    SIFRA_ELEMENTA    CHAR(18)      NOT NULL,
    NAZIV_ELEMENTA    VARCHAR(60)   NOT NULL,
    TIP_ELEMENTA      VARCHAR(30),
    AUTOR             VARCHAR(60),
    FORMAT_ELEMENTA   VARCHAR(30),
    USLOV_KORISCENJA  VARCHAR(255),
    CONSTRAINT PK_GRAFICKI_I_MUZICKI_ELEMENT PRIMARY KEY (SIFRA_ELEMENTA)
);

CREATE TABLE PROGRAMSKA_SEMA
(
    SIFRA_SEME       CHAR(18)     NOT NULL,
    SIFRA_UREDNIKA   CHAR(18)     NOT NULL,
    NAZIV_SEME       VARCHAR(60)  NOT NULL,
    SEZONA           VARCHAR(20),
    VERZIJA_SEME     VARCHAR(20),
    DATUM_OD         DATE,
    DATUM_DO         DATE,
    STATUS_SEME      VARCHAR(20),
    DATUM_USVAJANJA  DATE,
    CONSTRAINT PK_PROGRAMSKA_SEMA PRIMARY KEY (SIFRA_SEME)
);

CREATE TABLE PROGRAMSKA_CELINA
(
    SIFRA_SEME    CHAR(18)     NOT NULL,
    RB_CELINE     INTEGER      NOT NULL,
    NAZIV_CELINE  VARCHAR(60)  NOT NULL,
    TIP_CELINE    VARCHAR(30),
    DATUM         DATE,
    VREME_OD      TIME,
    VREME_DO      TIME,
    CONSTRAINT PK_PROGRAMSKA_CELINA PRIMARY KEY (SIFRA_SEME, RB_CELINE)
);

CREATE TABLE EMISIJA
(
    SIFRA_EMISIJE         CHAR(18)      NOT NULL,
    NAZIV_EMISIJE         VARCHAR(60)   NOT NULL,
    ZANR                  VARCHAR(30),
    FORMAT_EMISIJE        VARCHAR(30),
    PREDVIDJENO_TRAJANJE  INTEGER,
    CILJNA_PUBLIKA        VARCHAR(60),
    STATUS_EMISIJE        VARCHAR(20),
    PROGRAMSKI_ELABORAT   VARCHAR(255),
    CONSTRAINT PK_EMISIJA PRIMARY KEY (SIFRA_EMISIJE)
);

CREATE TABLE TERMIN_EMITOVANJA
(
    SIFRA_TERMINA       CHAR(18)     NOT NULL,
    SIFRA_SEME          CHAR(18)     NOT NULL,
    RB_CELINE           INTEGER      NOT NULL,
    SIFRA_EMISIJE       CHAR(18)     NOT NULL,
    DATUM               DATE         NOT NULL,
    VREME_POCETKA       TIME         NOT NULL,
    TRAJANJE_TERMINA    INTEGER,
    TIP_TERMINA         VARCHAR(30),
    ZONA_GLEDANOSTI     VARCHAR(20),
    STATUS_TERMINA      VARCHAR(20),
    REDNI_BROJ_REPRIZE  INTEGER,
    CONSTRAINT PK_TERMIN_EMITOVANJA PRIMARY KEY (SIFRA_TERMINA)
);

CREATE TABLE MEDIJSKI_SADRZAJ
(
    SIFRA_SADRZAJA     CHAR(18)     NOT NULL,
    NAZIV_SADRZAJA     VARCHAR(60)  NOT NULL,
    TRAJANJE           INTEGER,
    FORMAT_ZAPISA      VARCHAR(30),
    DATUM_ARHIVIRANJA  DATE,
    LOKACIJA_U_ARHIVI  VARCHAR(60),
    CONSTRAINT PK_MEDIJSKI_SADRZAJ PRIMARY KEY (SIFRA_SADRZAJA)
);

CREATE TABLE PRODUCIRANI_SADRZAJ
(
    SIFRA_SADRZAJA    CHAR(18)     NOT NULL,
    DATUM_PRODUKCIJE  DATE,
    VERZIJA_MASTERA   VARCHAR(20),
    CONSTRAINT PK_PRODUCIRANI_SADRZAJ PRIMARY KEY (SIFRA_SADRZAJA)
);

CREATE TABLE NABAVLJENI_SADRZAJ
(
    SIFRA_SADRZAJA     CHAR(18)       NOT NULL,
    BROJ_UGOVORA       CHAR(18)       NOT NULL,
    ZEMLJA_POREKLA     VARCHAR(60),
    CENA_NABAVKE       DECIMAL(12,2),
    DATUM_PREUZIMANJA  DATE,
    UGOVORENA_NAKNADA  DECIMAL(12,2),
    CONSTRAINT PK_NABAVLJENI_SADRZAJ PRIMARY KEY (SIFRA_SADRZAJA)
);

CREATE TABLE REKLAMNI_SADRZAJ
(
    SIFRA_SADRZAJA    CHAR(18)     NOT NULL,
    SIFRA_OGLASIVACA  CHAR(18)     NOT NULL,
    DATUM_PRIJEMA     DATE,
    STATUS            VARCHAR(20),
    CONSTRAINT PK_REKLAMNI_SADRZAJ PRIMARY KEY (SIFRA_SADRZAJA)
);

CREATE TABLE ZAPIS_O_EMITOVANJU
(
    SIFRA_TERMINA          CHAR(18)      NOT NULL,
    RB_EMITOVANJA          INTEGER       NOT NULL,
    SIFRA_SADRZAJA         CHAR(18)      NOT NULL,
    STATUS_REALIZACIJE     VARCHAR(20),
    STVARNO_VREME_POCETKA  TIME,
    STVARNO_TRAJANJE       INTEGER,
    NAPOMENA_O_SMETNJAMA   VARCHAR(255),
    OPERATER_EMITOVANJA    VARCHAR(60),
    CONSTRAINT PK_ZAPIS_O_EMITOVANJU PRIMARY KEY (SIFRA_TERMINA, RB_EMITOVANJA)
);

CREATE TABLE MONTAZA_SNIMKA
(
    SIFRA_SADRZAJA  CHAR(18)  NOT NULL,
    SIFRA_SNIMKA    CHAR(18)  NOT NULL,
    CONSTRAINT PK_MONTAZA_SNIMKA PRIMARY KEY (SIFRA_SADRZAJA, SIFRA_SNIMKA)
);

CREATE TABLE UGRADNJA_ELEMENTA
(
    SIFRA_SADRZAJA       CHAR(18)     NOT NULL,
    SIFRA_ELEMENTA       CHAR(18)     NOT NULL,
    VREME_POJAVLJIVANJA  TIME,
    NACIN_KORISCENJA     VARCHAR(60),
    CONSTRAINT PK_UGRADNJA_ELEMENTA PRIMARY KEY (SIFRA_SADRZAJA, SIFRA_ELEMENTA)
);

CREATE TABLE SADRZAJ_EMISIJE
(
    SIFRA_EMISIJE         CHAR(18)  NOT NULL,
    SIFRA_SADRZAJA        CHAR(18)  NOT NULL,
    REDNI_BROJ_U_EMISIJI  INTEGER,
    CONSTRAINT PK_SADRZAJ_EMISIJE PRIMARY KEY (SIFRA_EMISIJE, SIFRA_SADRZAJA)
);

CREATE TABLE PRAVO_KORISCENJA
(
    BROJ_LICENCE            CHAR(18)     NOT NULL,
    VRSTA_PRAVA             VARCHAR(30),
    DATUM_OD                DATE,
    DATUM_DO                DATE,
    DOZVOLJENO_EMITOVANJA   INTEGER,
    ISKORISCENO_EMITOVANJA  INTEGER,
    TERITORIJA              VARCHAR(60),
    NOSILAC_PRAVA           VARCHAR(60),
    CONSTRAINT PK_PRAVO_KORISCENJA PRIMARY KEY (BROJ_LICENCE)
);

CREATE TABLE POKRIVENOST_PRAVOM
(
    BROJ_LICENCE         CHAR(18)     NOT NULL,
    SIFRA_SADRZAJA       CHAR(18)     NOT NULL,
    OBLAST_POKRIVENOSTI  VARCHAR(60),
    CONSTRAINT PK_POKRIVENOST_PRAVOM PRIMARY KEY (BROJ_LICENCE, SIFRA_SADRZAJA)
);

CREATE TABLE POVRATNA_INFO_GLEDALACA
(
    BROJ_PRIJAVE     CHAR(18)      NOT NULL,
    SIFRA_EMISIJE    CHAR(18),
    DATUM_PRIJEMA    DATE,
    VRSTA_PRIJAVE    VARCHAR(30),
    KANAL_PRIJEMA    VARCHAR(30),
    SADRZAJ_PRIJAVE  VARCHAR(255),
    STATUS_OBRADE    VARCHAR(20),
    DATUM_ODGOVORA   DATE,
    PROFIL_GLEDAOCA  VARCHAR(60),
    CONSTRAINT PK_POVRATNA_INFO_GLEDALACA PRIMARY KEY (BROJ_PRIJAVE)
);

CREATE TABLE MERENJE_GLEDANOSTI
(
    SIFRA_MERENJA      CHAR(18)      NOT NULL,
    DATUM_MERENJA      DATE,
    IZVOR_MERENJA      VARCHAR(60),
    CILJNA_GRUPA       VARCHAR(60),
    RATING             DECIMAL(5,2),
    SHARE_UDEO         DECIMAL(5,2),
    BROJ_GLEDALACA     INTEGER,
    PROSECNO_GLEDANJE  INTEGER,
    CONSTRAINT PK_MERENJE_GLEDANOSTI PRIMARY KEY (SIFRA_MERENJA)
);

CREATE TABLE MERENJE_EMISIJE
(
    SIFRA_MERENJA     CHAR(18)      NOT NULL,
    SIFRA_EMISIJE     CHAR(18)      NOT NULL,
    OSTVARENI_RATING  DECIMAL(5,2),
    UDEO_U_TERMINU    DECIMAL(5,2),
    CONSTRAINT PK_MERENJE_EMISIJE PRIMARY KEY (SIFRA_MERENJA, SIFRA_EMISIJE)
);

CREATE TABLE CENOVNIK_REKL_TERMINA
(
    SIFRA_CENOVNIKA       CHAR(18)       NOT NULL,
    VAZI_OD               DATE,
    VAZI_DO               DATE,
    ZONA                  VARCHAR(30),
    CENA_PO_SEKUNDI       DECIMAL(12,2),
    TIP_CENOVNOG_PAKETA   VARCHAR(30),
    OPIS_CENOVNOG_PAKETA  VARCHAR(255),
    CONSTRAINT PK_CENOVNIK_REKL_TERMINA PRIMARY KEY (SIFRA_CENOVNIKA)
);

CREATE TABLE REKLAMNI_BLOK
(
    SIFRA_BLOKA         CHAR(18)      NOT NULL,
    SIFRA_TERMINA       CHAR(18)      NOT NULL,
    SIFRA_CENOVNIKA     CHAR(18)      NOT NULL,
    DATUM               DATE,
    VREME_POCETKA       TIME,
    TRAJANJE_BLOKA      INTEGER,
    ZAKUPLJENO_SEKUNDI  INTEGER,
    SLOBODNO_SEKUNDI    INTEGER,
    ISKORISCENOST       DECIMAL(5,2),
    STATUS_BLOKA        VARCHAR(20),
    CONSTRAINT PK_REKLAMNI_BLOK PRIMARY KEY (SIFRA_BLOKA)
);

CREATE TABLE EMITOVANJE_REKLAME
(
    SIFRA_BLOKA        CHAR(18)       NOT NULL,
    RB_U_BLOKU         INTEGER        NOT NULL,
    SIFRA_SADRZAJA     CHAR(18)       NOT NULL,
    BROJ_UGOVORA       CHAR(18)       NOT NULL,
    RB_STAVKE_UGOVORA  INTEGER        NOT NULL,
    DATUM_EMITOVANJA   DATE,
    VREME_EMITOVANJA   TIME,
    TRAJANJE_SPOTA     INTEGER,
    NAPLACENI_IZNOS    DECIMAL(12,2),
    STATUS_NAPLATE     VARCHAR(20),
    CONSTRAINT PK_EMITOVANJE_REKLAME PRIMARY KEY (SIFRA_BLOKA, RB_U_BLOKU)
);

CREATE TABLE KLIJENT
(
    SIFRA_KLIJENTA  CHAR(18)     NOT NULL,
    NAZIV_KLIJENTA  VARCHAR(60)  NOT NULL,
    PIB             CHAR(9),
    MATICNI_BROJ    CHAR(8),
    ULICA_I_BROJ    VARCHAR(60),
    GRAD            VARCHAR(30),
    POSTANSKI_BROJ  CHAR(5),
    KONTAKT_OSOBA   VARCHAR(60),
    CONSTRAINT PK_KLIJENT PRIMARY KEY (SIFRA_KLIJENTA)
);

CREATE TABLE OGLASIVAC
(
    SIFRA_KLIJENTA   CHAR(18)       NOT NULL,
    BRANSA           VARCHAR(60),
    GODISNJI_BUDZET  DECIMAL(12,2),
    CONSTRAINT PK_OGLASIVAC PRIMARY KEY (SIFRA_KLIJENTA)
);

CREATE TABLE KUPAC_SADRZAJA
(
    SIFRA_KLIJENTA         CHAR(18)     NOT NULL,
    TIP_MEDIJA             VARCHAR(30),
    TERITORIJA_EMITOVANJA  VARCHAR(60),
    CONSTRAINT PK_KUPAC_SADRZAJA PRIMARY KEY (SIFRA_KLIJENTA)
);

CREATE TABLE UGOVOR
(
    BROJ_UGOVORA     CHAR(18)       NOT NULL,
    SIFRA_KLIJENTA   CHAR(18),
    DATUM_SKLAPANJA  DATE,
    VAZI_OD          DATE,
    VAZI_DO          DATE,
    UKUPNA_VREDNOST  DECIMAL(12,2),
    STATUS_UGOVORA   VARCHAR(20),
    CONSTRAINT PK_UGOVOR PRIMARY KEY (BROJ_UGOVORA)
);

CREATE TABLE STAVKA_UGOVORA
(
    BROJ_UGOVORA      CHAR(18)       NOT NULL,
    RB_STAVKE         INTEGER        NOT NULL,
    OPIS_STAVKE       VARCHAR(255),
    KOLICINA_SEKUNDE  INTEGER,
    JEDINICNA_CENA    DECIMAL(12,2),
    POPUST            DECIMAL(5,2),
    VREDNOST_STAVKE   DECIMAL(12,2),
    CONSTRAINT PK_STAVKA_UGOVORA PRIMARY KEY (BROJ_UGOVORA, RB_STAVKE)
);

CREATE TABLE UGOVOR_O_OGLASAVANJU
(
    BROJ_UGOVORA       CHAR(18)      NOT NULL,
    UGOVORENI_TERMINI  VARCHAR(255),
    CONSTRAINT PK_UGOVOR_O_OGLASAVANJU PRIMARY KEY (BROJ_UGOVORA)
);

CREATE TABLE UGOVOR_O_PRODAJI_TV_SADRZAJA
(
    BROJ_UGOVORA            CHAR(18)      NOT NULL,
    PRENOS_VLASNISTVA       VARCHAR(20),
    OBIM_USTUPLJENIH_PRAVA  VARCHAR(255),
    CONSTRAINT PK_UGOVOR_O_PRODAJI_TV_SADRZAJ PRIMARY KEY (BROJ_UGOVORA)
);

CREATE TABLE UGOVOR_O_NABAVCI
(
    BROJ_UGOVORA        CHAR(18)      NOT NULL,
    SIFRA_DOBAVLJACA    CHAR(18)      NOT NULL,
    VRSTA_REKLAMIRANJA  VARCHAR(30),
    ROK_ISPORUKE        DATE,
    USLOVI_PLACANJA     VARCHAR(255),
    CONSTRAINT PK_UGOVOR_O_NABAVCI PRIMARY KEY (BROJ_UGOVORA)
);

CREATE TABLE USTUPANJE_SADRZAJA
(
    BROJ_UGOVORA    CHAR(18)       NOT NULL,
    SIFRA_SADRZAJA  CHAR(18)       NOT NULL,
    UGOVORENA_CENA  DECIMAL(12,2),
    OBIM_USTUPANJA  VARCHAR(255),
    CONSTRAINT PK_USTUPANJE_SADRZAJA PRIMARY KEY (BROJ_UGOVORA, SIFRA_SADRZAJA)
);

CREATE TABLE PLAN_NABAVKE
(
    SIFRA_PLANA      CHAR(18)       NOT NULL,
    GODINA_PLANA     INTEGER,
    DATUM_DONOSENJA  DATE,
    STATUS_PLANA     VARCHAR(20),
    UKUPNA_VREDNOST  DECIMAL(12,2),
    DONOSILAC_PLANA  VARCHAR(60),
    CONSTRAINT PK_PLAN_NABAVKE PRIMARY KEY (SIFRA_PLANA)
);

CREATE TABLE ZAHTEV_ZA_NABAVKU
(
    BROJ_ZAHTEVA         CHAR(18)       NOT NULL,
    SIFRA_JEDINICE       CHAR(18)       NOT NULL,
    SIFRA_PLANA          CHAR(18),
    DATUM_ZAHTEVA        DATE,
    VRSTA_NABAVKE        VARCHAR(30),
    PREDMET_ZAHTEVA      VARCHAR(255),
    OBRAZLOZENJE         VARCHAR(255),
    STATUS_ZAHTEVA       VARCHAR(20),
    PRIORITET            VARCHAR(20),
    PROCENJENA_VREDNOST  DECIMAL(12,2),
    CONSTRAINT PK_ZAHTEV_ZA_NABAVKU PRIMARY KEY (BROJ_ZAHTEVA)
);

CREATE TABLE STAVKA_PLANA_NABAVKE
(
    SIFRA_PLANA        CHAR(18)       NOT NULL,
    RB_STAVKE          INTEGER        NOT NULL,
    OPIS_ARTIKLA       VARCHAR(255),
    KOLICINA           INTEGER,
    JEDINICA_MERE      VARCHAR(20),
    PROCENJENA_CENA    DECIMAL(12,2),
    PLANIRANI_KVARTAL  VARCHAR(20),
    CONSTRAINT PK_STAVKA_PLANA_NABAVKE PRIMARY KEY (SIFRA_PLANA, RB_STAVKE)
);

CREATE TABLE DOBAVLJAC
(
    SIFRA_DOBAVLJACA  CHAR(18)      NOT NULL,
    NAZIV_DOBAVLJACA  VARCHAR(60)   NOT NULL,
    PIB               CHAR(9),
    MATICNI_BROJ      CHAR(8),
    ADRESA            VARCHAR(60),
    OCENA_DOBAVLJACA  DECIMAL(5,2),
    CONSTRAINT PK_DOBAVLJAC PRIMARY KEY (SIFRA_DOBAVLJACA)
);

CREATE TABLE DOBAVLJAC_TV_SADRZAJA
(
    SIFRA_DOBAVLJACA  CHAR(18)      NOT NULL,
    VRSTA_SADRZAJA    VARCHAR(30),
    KATALOG_PONUDE    VARCHAR(255),
    CONSTRAINT PK_DOBAVLJAC_TV_SADRZAJA PRIMARY KEY (SIFRA_DOBAVLJACA)
);

CREATE TABLE DOBAVLJAC_OPREME_I_MATERIJALA
(
    SIFRA_DOBAVLJACA  CHAR(18)      NOT NULL,
    ASORTIMAN         VARCHAR(255),
    OVLASCENI_SERVIS  VARCHAR(20),
    CONSTRAINT PK_DOBAVLJAC_OPREME_I_MATERIJA PRIMARY KEY (SIFRA_DOBAVLJACA)
);

CREATE TABLE PONUDA_DOBAVLJACA
(
    BROJ_PONUDE       CHAR(18)       NOT NULL,
    SIFRA_DOBAVLJACA  CHAR(18)       NOT NULL,
    DATUM_PRIJEMA     DATE,
    VAZI_DO           DATE,
    UKUPNA_CENA       DECIMAL(12,2),
    ROK_ISPORUKE      DATE,
    USLOVI_PLACANJA   VARCHAR(255),
    STATUS_PONUDE     VARCHAR(20),
    UKUPNO_BODOVA     DECIMAL(5,2),
    CONSTRAINT PK_PONUDA_DOBAVLJACA PRIMARY KEY (BROJ_PONUDE)
);

CREATE TABLE PONUDJENA_STAVKA
(
    SIFRA_PLANA     CHAR(18)       NOT NULL,
    RB_STAVKE       INTEGER        NOT NULL,
    BROJ_PONUDE     CHAR(18)       NOT NULL,
    PONUDJENA_CENA  DECIMAL(12,2),
    ROK_ZA_STAVKU   DATE,
    CONSTRAINT PK_PONUDJENA_STAVKA PRIMARY KEY (SIFRA_PLANA, RB_STAVKE, BROJ_PONUDE)
);

CREATE TABLE KRITERIJUM_VREDNOVANJA
(
    SIFRA_KRITERIJUMA  CHAR(18)      NOT NULL,
    NAZIV_KRITERIJUMA  VARCHAR(60)   NOT NULL,
    NACIN_BODOVANJA    VARCHAR(60),
    OPIS_KRITERIJUMA   VARCHAR(255),
    CONSTRAINT PK_KRITERIJUM_VREDNOVANJA PRIMARY KEY (SIFRA_KRITERIJUMA)
);

CREATE TABLE OCENA_PONUDE
(
    BROJ_PONUDE        CHAR(18)      NOT NULL,
    SIFRA_KRITERIJUMA  CHAR(18)      NOT NULL,
    BROJ_BODOVA        DECIMAL(5,2),
    KOMENTAR_OCENE     VARCHAR(255),
    CONSTRAINT PK_OCENA_PONUDE PRIMARY KEY (BROJ_PONUDE, SIFRA_KRITERIJUMA)
);

CREATE TABLE NARUDZBENICA
(
    BROJ_NARUDZBENICE  CHAR(18)       NOT NULL,
    SIFRA_DOBAVLJACA   CHAR(18)       NOT NULL,
    DATUM_IZDAVANJA    DATE,
    ROK_ISPORUKE       DATE,
    MESTO_ISPORUKE     VARCHAR(60),
    UKUPAN_IZNOS       DECIMAL(12,2),
    STATUS_NARUDZBINE  VARCHAR(20),
    CONSTRAINT PK_NARUDZBENICA PRIMARY KEY (BROJ_NARUDZBENICE)
);

CREATE TABLE STAVKA_NARUDZBENICE
(
    BROJ_NARUDZBENICE  CHAR(18)       NOT NULL,
    RB_STAVKE          INTEGER        NOT NULL,
    NAZIV_ARTIKLA      VARCHAR(60),
    KOLICINA           INTEGER,
    JEDINICNA_CENA     DECIMAL(12,2),
    STATUS_STAVKE      VARCHAR(20),
    VREDNOST_STAVKE    DECIMAL(12,2),
    CONSTRAINT PK_STAVKA_NARUDZBENICE PRIMARY KEY (BROJ_NARUDZBENICE, RB_STAVKE)
);

CREATE TABLE PRIJEMNICA
(
    BROJ_PRIJEMNICE      CHAR(18)      NOT NULL,
    BROJ_NARUDZBENICE    CHAR(18)      NOT NULL,
    BROJ_FAKTURE         CHAR(18),
    DATUM_PRIJEMA        DATE,
    BROJ_OTPREMNICE      VARCHAR(30),
    PRIMIO_MAGACIONER    VARCHAR(60),
    ISPRAVNOST_ISPORUKE  VARCHAR(20),
    NAPOMENA             VARCHAR(255),
    CONSTRAINT PK_PRIJEMNICA PRIMARY KEY (BROJ_PRIJEMNICE)
);

CREATE TABLE PRIJEM_STAVKE
(
    BROJ_PRIJEMNICE       CHAR(18)      NOT NULL,
    BROJ_NARUDZBENICE     CHAR(18)      NOT NULL,
    RB_STAVKE             INTEGER       NOT NULL,
    PRIMLJENA_KOLICINA    INTEGER,
    UTVRDJENO_ODSTUPANJE  VARCHAR(255),
    CONSTRAINT PK_PRIJEM_STAVKE PRIMARY KEY (BROJ_PRIJEMNICE, BROJ_NARUDZBENICE, RB_STAVKE)
);

CREATE TABLE REKLAMACIJA
(
    BROJ_REKLAMACIJE    CHAR(18)       NOT NULL,
    BROJ_PRIJEMNICE     CHAR(18)       NOT NULL,
    DATUM_REKLAMACIJE   DATE,
    RAZLOG_REKLAMACIJE  VARCHAR(60),
    OPIS_NEDOSTATKA     VARCHAR(255),
    STATUS_REKLAMACIJE  VARCHAR(20),
    DATUM_RESENJA       DATE,
    REKLAMIRANI_IZNOS   DECIMAL(12,2),
    NACIN_RESAVANJA     VARCHAR(60),
    CONSTRAINT PK_REKLAMACIJA PRIMARY KEY (BROJ_REKLAMACIJE)
);

CREATE TABLE REKLAMIRANA_STAVKA
(
    BROJ_REKLAMACIJE   CHAR(18)  NOT NULL,
    BROJ_NARUDZBENICE  CHAR(18)  NOT NULL,
    RB_STAVKE          INTEGER   NOT NULL,
    CONSTRAINT PK_REKLAMIRANA_STAVKA PRIMARY KEY (BROJ_REKLAMACIJE, BROJ_NARUDZBENICE, RB_STAVKE)
);

CREATE TABLE FAKTURA
(
    BROJ_FAKTURE       CHAR(18)       NOT NULL,
    BROJ_UGOVORA       CHAR(18),
    DATUM_IZDAVANJA    DATE,
    ROK_PLACANJA       DATE,
    SMER               VARCHAR(20),
    OSNOVICA           DECIMAL(12,2),
    IZNOS_PDV          DECIMAL(12,2),
    STATUS_PLACANJA    VARCHAR(20),
    IZNOS_ZA_PLACANJE  DECIMAL(12,2),
    CONSTRAINT PK_FAKTURA PRIMARY KEY (BROJ_FAKTURE)
);

CREATE TABLE STAVKA_FAKTURE
(
    BROJ_FAKTURE     CHAR(18)       NOT NULL,
    RB_STAVKE        INTEGER        NOT NULL,
    OPIS_STAVKE      VARCHAR(255),
    KOLICINA         INTEGER,
    JEDINICNA_CENA   DECIMAL(12,2),
    STOPA_PDV        DECIMAL(5,2),
    VREDNOST_STAVKE  DECIMAL(12,2),
    CONSTRAINT PK_STAVKA_FAKTURE PRIMARY KEY (BROJ_FAKTURE, RB_STAVKE)
);

CREATE TABLE NALOG_ZA_PLACANJE
(
    BROJ_NALOGA        CHAR(18)       NOT NULL,
    BROJ_FAKTURE       CHAR(18)       NOT NULL,
    DATUM_NALOGA       DATE,
    IZNOS_NALOGA       DECIMAL(12,2),
    SVRHA_PLACANJA     VARCHAR(255),
    DATUM_REALIZACIJE  DATE,
    STATUS_NALOGA      VARCHAR(20),
    RACUN_PRIMAOCA     VARCHAR(30),
    ODOBRIO            VARCHAR(60),
    CONSTRAINT PK_NALOG_ZA_PLACANJE PRIMARY KEY (BROJ_NALOGA)
);

ALTER TABLE ORGANIZACIONA_JEDINICA
    ADD CONSTRAINT FK_ORGJED_PODREDJENA FOREIGN KEY (SIFRA_NADREDJENE_JEDINICE)
    REFERENCES ORGANIZACIONA_JEDINICA (SIFRA_JEDINICE);

ALTER TABLE ZAPOSLENI
    ADD CONSTRAINT FK_ZAPOSLENI_RADI_U FOREIGN KEY (SIFRA_JEDINICE)
    REFERENCES ORGANIZACIONA_JEDINICA (SIFRA_JEDINICE);

ALTER TABLE UREDNIK
    ADD CONSTRAINT FK_UREDNIK_ZAPOSLENI FOREIGN KEY (SIFRA_ZAPOSLENOG)
    REFERENCES ZAPOSLENI (SIFRA_ZAPOSLENOG);

ALTER TABLE NOVINAR_REPORTER
    ADD CONSTRAINT FK_NOVINAR_ZAPOSLENI FOREIGN KEY (SIFRA_ZAPOSLENOG)
    REFERENCES ZAPOSLENI (SIFRA_ZAPOSLENOG);

ALTER TABLE TEHNICKO_OSOBLJE
    ADD CONSTRAINT FK_TEHOSOB_ZAPOSLENI FOREIGN KEY (SIFRA_ZAPOSLENOG)
    REFERENCES ZAPOSLENI (SIFRA_ZAPOSLENOG);

ALTER TABLE REFERENT
    ADD CONSTRAINT FK_REFERENT_ZAPOSLENI FOREIGN KEY (SIFRA_ZAPOSLENOG)
    REFERENCES ZAPOSLENI (SIFRA_ZAPOSLENOG);

ALTER TABLE SERVISERI
    ADD CONSTRAINT FK_SERVISERI_ZAPOSLENI FOREIGN KEY (SIFRA_ZAPOSLENOG)
    REFERENCES ZAPOSLENI (SIFRA_ZAPOSLENOG);

ALTER TABLE SNIMATELJSKA_OPREMA
    ADD CONSTRAINT FK_SNIMOPR_OPREMA FOREIGN KEY (INVENTARSKI_BROJ)
    REFERENCES OPREMA (INVENTARSKI_BROJ);

ALTER TABLE STUDIJSKA_I_EMISIONA_OPREMA
    ADD CONSTRAINT FK_STUDOPR_OPREMA FOREIGN KEY (INVENTARSKI_BROJ)
    REFERENCES OPREMA (INVENTARSKI_BROJ);

ALTER TABLE AUDIO_OPREMA
    ADD CONSTRAINT FK_AUDIOOPR_STUDOPR FOREIGN KEY (INVENTARSKI_BROJ)
    REFERENCES STUDIJSKA_I_EMISIONA_OPREMA (INVENTARSKI_BROJ);

ALTER TABLE SVETLOSNA_OPREMA
    ADD CONSTRAINT FK_SVETLOPR_STUDOPR FOREIGN KEY (INVENTARSKI_BROJ)
    REFERENCES STUDIJSKA_I_EMISIONA_OPREMA (INVENTARSKI_BROJ);

ALTER TABLE ZADUZENJE_OPREME
    ADD CONSTRAINT FK_ZADUZ_ZAPOSLENI FOREIGN KEY (SIFRA_ZAPOSLENOG)
    REFERENCES ZAPOSLENI (SIFRA_ZAPOSLENOG);

ALTER TABLE ZADUZENJE_OPREME
    ADD CONSTRAINT FK_ZADUZ_OPREMA FOREIGN KEY (INVENTARSKI_BROJ)
    REFERENCES OPREMA (INVENTARSKI_BROJ);

ALTER TABLE SERVISIRANJE_OPREME
    ADD CONSTRAINT FK_SERVIS_SERVISERI FOREIGN KEY (SIFRA_ZAPOSLENOG)
    REFERENCES SERVISERI (SIFRA_ZAPOSLENOG);

ALTER TABLE SERVISIRANJE_OPREME
    ADD CONSTRAINT FK_SERVIS_OPREMA FOREIGN KEY (INVENTARSKI_BROJ)
    REFERENCES OPREMA (INVENTARSKI_BROJ);

ALTER TABLE PROJEKAT_PRODUKCIJE
    ADD CONSTRAINT FK_PROJEKAT_UREDJUJE FOREIGN KEY (SIFRA_UREDNIKA)
    REFERENCES UREDNIK (SIFRA_ZAPOSLENOG);

ALTER TABLE PROJEKAT_PRODUKCIJE
    ADD CONSTRAINT FK_PROJEKAT_PROIZVODI FOREIGN KEY (SIFRA_EMISIJE)
    REFERENCES EMISIJA (SIFRA_EMISIJE);

ALTER TABLE AKTIVNOST_PRODUKCIJE
    ADD CONSTRAINT FK_AKTIVNOST_PROJEKAT FOREIGN KEY (SIFRA_PROJEKTA)
    REFERENCES PROJEKAT_PRODUKCIJE (SIFRA_PROJEKTA);

ALTER TABLE TROSAK_PRODUKCIJE
    ADD CONSTRAINT FK_TROSAK_IZAZIVA FOREIGN KEY (SIFRA_PROJEKTA, RB_AKTIVNOSTI)
    REFERENCES AKTIVNOST_PRODUKCIJE (SIFRA_PROJEKTA, RB_AKTIVNOSTI);

ALTER TABLE TROSAK_PRODUKCIJE
    ADD CONSTRAINT FK_TROSAK_DOKUMENTOVAN FOREIGN KEY (BROJ_FAKTURE)
    REFERENCES FAKTURA (BROJ_FAKTURE);

ALTER TABLE ANGAZOVANJE_NA_AKTIVNOSTI
    ADD CONSTRAINT FK_ANGAZ_AKTIVNOST FOREIGN KEY (SIFRA_PROJEKTA, RB_AKTIVNOSTI)
    REFERENCES AKTIVNOST_PRODUKCIJE (SIFRA_PROJEKTA, RB_AKTIVNOSTI);

ALTER TABLE ANGAZOVANJE_NA_AKTIVNOSTI
    ADD CONSTRAINT FK_ANGAZ_ZAPOSLENI FOREIGN KEY (SIFRA_ZAPOSLENOG)
    REFERENCES ZAPOSLENI (SIFRA_ZAPOSLENOG);

ALTER TABLE REZERVACIJA_OPREME
    ADD CONSTRAINT FK_REZERV_AKTIVNOST FOREIGN KEY (SIFRA_PROJEKTA, RB_AKTIVNOSTI)
    REFERENCES AKTIVNOST_PRODUKCIJE (SIFRA_PROJEKTA, RB_AKTIVNOSTI);

ALTER TABLE REZERVACIJA_OPREME
    ADD CONSTRAINT FK_REZERV_OPREMA FOREIGN KEY (INVENTARSKI_BROJ)
    REFERENCES OPREMA (INVENTARSKI_BROJ);

ALTER TABLE SIROVI_SNIMAK
    ADD CONSTRAINT FK_SNIMAK_SNIMLJEN_NA FOREIGN KEY (SIFRA_PROJEKTA, RB_AKTIVNOSTI)
    REFERENCES AKTIVNOST_PRODUKCIJE (SIFRA_PROJEKTA, RB_AKTIVNOSTI);

ALTER TABLE PROGRAMSKA_SEMA
    ADD CONSTRAINT FK_PSEMA_ODOBRAVA FOREIGN KEY (SIFRA_UREDNIKA)
    REFERENCES UREDNIK (SIFRA_ZAPOSLENOG);

ALTER TABLE PROGRAMSKA_CELINA
    ADD CONSTRAINT FK_PCELINA_PSEMA FOREIGN KEY (SIFRA_SEME)
    REFERENCES PROGRAMSKA_SEMA (SIFRA_SEME);

ALTER TABLE TERMIN_EMITOVANJA
    ADD CONSTRAINT FK_TERMIN_OBUHVATA FOREIGN KEY (SIFRA_SEME, RB_CELINE)
    REFERENCES PROGRAMSKA_CELINA (SIFRA_SEME, RB_CELINE);

ALTER TABLE TERMIN_EMITOVANJA
    ADD CONSTRAINT FK_TERMIN_PLANIRANA FOREIGN KEY (SIFRA_EMISIJE)
    REFERENCES EMISIJA (SIFRA_EMISIJE);

ALTER TABLE PRODUCIRANI_SADRZAJ
    ADD CONSTRAINT FK_MSPROD_MSADRZAJ FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES MEDIJSKI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE NABAVLJENI_SADRZAJ
    ADD CONSTRAINT FK_MSNAB_MSADRZAJ FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES MEDIJSKI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE NABAVLJENI_SADRZAJ
    ADD CONSTRAINT FK_MSNAB_NABAVLJEN_PO FOREIGN KEY (BROJ_UGOVORA)
    REFERENCES UGOVOR_O_NABAVCI (BROJ_UGOVORA);

ALTER TABLE REKLAMNI_SADRZAJ
    ADD CONSTRAINT FK_MSREK_MSADRZAJ FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES MEDIJSKI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE REKLAMNI_SADRZAJ
    ADD CONSTRAINT FK_MSREK_DOSTAVLJA FOREIGN KEY (SIFRA_OGLASIVACA)
    REFERENCES OGLASIVAC (SIFRA_KLIJENTA);

ALTER TABLE ZAPIS_O_EMITOVANJU
    ADD CONSTRAINT FK_ZAPISEM_REALIZOVAN FOREIGN KEY (SIFRA_TERMINA)
    REFERENCES TERMIN_EMITOVANJA (SIFRA_TERMINA);

ALTER TABLE ZAPIS_O_EMITOVANJU
    ADD CONSTRAINT FK_ZAPISEM_EVIDENTIRA FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES MEDIJSKI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE MONTAZA_SNIMKA
    ADD CONSTRAINT FK_MONTAZA_MSADRZAJ FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES MEDIJSKI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE MONTAZA_SNIMKA
    ADD CONSTRAINT FK_MONTAZA_SNIMAK FOREIGN KEY (SIFRA_SNIMKA)
    REFERENCES SIROVI_SNIMAK (SIFRA_SNIMKA);

ALTER TABLE UGRADNJA_ELEMENTA
    ADD CONSTRAINT FK_UGRADNJA_MSADRZAJ FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES MEDIJSKI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE UGRADNJA_ELEMENTA
    ADD CONSTRAINT FK_UGRADNJA_ELEMENT FOREIGN KEY (SIFRA_ELEMENTA)
    REFERENCES GRAFICKI_I_MUZICKI_ELEMENT (SIFRA_ELEMENTA);

ALTER TABLE SADRZAJ_EMISIJE
    ADD CONSTRAINT FK_SADREM_EMISIJA FOREIGN KEY (SIFRA_EMISIJE)
    REFERENCES EMISIJA (SIFRA_EMISIJE);

ALTER TABLE SADRZAJ_EMISIJE
    ADD CONSTRAINT FK_SADREM_MSADRZAJ FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES MEDIJSKI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE POKRIVENOST_PRAVOM
    ADD CONSTRAINT FK_POKRIV_PRAVO FOREIGN KEY (BROJ_LICENCE)
    REFERENCES PRAVO_KORISCENJA (BROJ_LICENCE);

ALTER TABLE POKRIVENOST_PRAVOM
    ADD CONSTRAINT FK_POKRIV_MSADRZAJ FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES MEDIJSKI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE POVRATNA_INFO_GLEDALACA
    ADD CONSTRAINT FK_POVRINF_EMISIJA FOREIGN KEY (SIFRA_EMISIJE)
    REFERENCES EMISIJA (SIFRA_EMISIJE);

ALTER TABLE MERENJE_EMISIJE
    ADD CONSTRAINT FK_MERENJEEM_MERENJE FOREIGN KEY (SIFRA_MERENJA)
    REFERENCES MERENJE_GLEDANOSTI (SIFRA_MERENJA);

ALTER TABLE MERENJE_EMISIJE
    ADD CONSTRAINT FK_MERENJEEM_EMISIJA FOREIGN KEY (SIFRA_EMISIJE)
    REFERENCES EMISIJA (SIFRA_EMISIJE);

ALTER TABLE REKLAMNI_BLOK
    ADD CONSTRAINT FK_RBLOK_ZAKUPLJEN_U FOREIGN KEY (SIFRA_TERMINA)
    REFERENCES TERMIN_EMITOVANJA (SIFRA_TERMINA);

ALTER TABLE REKLAMNI_BLOK
    ADD CONSTRAINT FK_RBLOK_TARIFIRAN FOREIGN KEY (SIFRA_CENOVNIKA)
    REFERENCES CENOVNIK_REKL_TERMINA (SIFRA_CENOVNIKA);

ALTER TABLE EMITOVANJE_REKLAME
    ADD CONSTRAINT FK_EMREK_SADRZI_SPOT FOREIGN KEY (SIFRA_BLOKA)
    REFERENCES REKLAMNI_BLOK (SIFRA_BLOKA);

ALTER TABLE EMITOVANJE_REKLAME
    ADD CONSTRAINT FK_EMREK_PRIKAZUJE FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES REKLAMNI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE EMITOVANJE_REKLAME
    ADD CONSTRAINT FK_EMREK_UGOVOREN FOREIGN KEY (BROJ_UGOVORA, RB_STAVKE_UGOVORA)
    REFERENCES STAVKA_UGOVORA (BROJ_UGOVORA, RB_STAVKE);

ALTER TABLE OGLASIVAC
    ADD CONSTRAINT FK_OGLASIVAC_KLIJENT FOREIGN KEY (SIFRA_KLIJENTA)
    REFERENCES KLIJENT (SIFRA_KLIJENTA);

ALTER TABLE KUPAC_SADRZAJA
    ADD CONSTRAINT FK_KUPACSAD_KLIJENT FOREIGN KEY (SIFRA_KLIJENTA)
    REFERENCES KLIJENT (SIFRA_KLIJENTA);

ALTER TABLE UGOVOR
    ADD CONSTRAINT FK_UGOVOR_SKLAPA FOREIGN KEY (SIFRA_KLIJENTA)
    REFERENCES KLIJENT (SIFRA_KLIJENTA);

ALTER TABLE STAVKA_UGOVORA
    ADD CONSTRAINT FK_STUGOV_PRECIZIRA FOREIGN KEY (BROJ_UGOVORA)
    REFERENCES UGOVOR (BROJ_UGOVORA);

ALTER TABLE UGOVOR_O_OGLASAVANJU
    ADD CONSTRAINT FK_UGOGL_UGOVOR FOREIGN KEY (BROJ_UGOVORA)
    REFERENCES UGOVOR (BROJ_UGOVORA);

ALTER TABLE UGOVOR_O_PRODAJI_TV_SADRZAJA
    ADD CONSTRAINT FK_UGPROD_UGOVOR FOREIGN KEY (BROJ_UGOVORA)
    REFERENCES UGOVOR (BROJ_UGOVORA);

ALTER TABLE UGOVOR_O_NABAVCI
    ADD CONSTRAINT FK_UGNAB_UGOVOR FOREIGN KEY (BROJ_UGOVORA)
    REFERENCES UGOVOR (BROJ_UGOVORA);

ALTER TABLE UGOVOR_O_NABAVCI
    ADD CONSTRAINT FK_UGNAB_UGOVARA FOREIGN KEY (SIFRA_DOBAVLJACA)
    REFERENCES DOBAVLJAC (SIFRA_DOBAVLJACA);

ALTER TABLE USTUPANJE_SADRZAJA
    ADD CONSTRAINT FK_USTUP_UGPROD FOREIGN KEY (BROJ_UGOVORA)
    REFERENCES UGOVOR_O_PRODAJI_TV_SADRZAJA (BROJ_UGOVORA);

ALTER TABLE USTUPANJE_SADRZAJA
    ADD CONSTRAINT FK_USTUP_MSPROD FOREIGN KEY (SIFRA_SADRZAJA)
    REFERENCES PRODUCIRANI_SADRZAJ (SIFRA_SADRZAJA);

ALTER TABLE ZAHTEV_ZA_NABAVKU
    ADD CONSTRAINT FK_ZAHNAB_PODNOSI FOREIGN KEY (SIFRA_JEDINICE)
    REFERENCES ORGANIZACIONA_JEDINICA (SIFRA_JEDINICE);

ALTER TABLE ZAHTEV_ZA_NABAVKU
    ADD CONSTRAINT FK_ZAHNAB_UVRSTEN_U FOREIGN KEY (SIFRA_PLANA)
    REFERENCES PLAN_NABAVKE (SIFRA_PLANA);

ALTER TABLE STAVKA_PLANA_NABAVKE
    ADD CONSTRAINT FK_STPLAN_PLAN FOREIGN KEY (SIFRA_PLANA)
    REFERENCES PLAN_NABAVKE (SIFRA_PLANA);

ALTER TABLE DOBAVLJAC_TV_SADRZAJA
    ADD CONSTRAINT FK_DOBTVSAD_DOBAVLJAC FOREIGN KEY (SIFRA_DOBAVLJACA)
    REFERENCES DOBAVLJAC (SIFRA_DOBAVLJACA);

ALTER TABLE DOBAVLJAC_OPREME_I_MATERIJALA
    ADD CONSTRAINT FK_DOBOPR_DOBAVLJAC FOREIGN KEY (SIFRA_DOBAVLJACA)
    REFERENCES DOBAVLJAC (SIFRA_DOBAVLJACA);

ALTER TABLE PONUDA_DOBAVLJACA
    ADD CONSTRAINT FK_PONUDA_DOSTAVIO FOREIGN KEY (SIFRA_DOBAVLJACA)
    REFERENCES DOBAVLJAC (SIFRA_DOBAVLJACA);

ALTER TABLE PONUDJENA_STAVKA
    ADD CONSTRAINT FK_PONSTAV_STPLAN FOREIGN KEY (SIFRA_PLANA, RB_STAVKE)
    REFERENCES STAVKA_PLANA_NABAVKE (SIFRA_PLANA, RB_STAVKE);

ALTER TABLE PONUDJENA_STAVKA
    ADD CONSTRAINT FK_PONSTAV_PONUDA FOREIGN KEY (BROJ_PONUDE)
    REFERENCES PONUDA_DOBAVLJACA (BROJ_PONUDE);

ALTER TABLE OCENA_PONUDE
    ADD CONSTRAINT FK_OCENA_PONUDA FOREIGN KEY (BROJ_PONUDE)
    REFERENCES PONUDA_DOBAVLJACA (BROJ_PONUDE);

ALTER TABLE OCENA_PONUDE
    ADD CONSTRAINT FK_OCENA_KRITERIJUM FOREIGN KEY (SIFRA_KRITERIJUMA)
    REFERENCES KRITERIJUM_VREDNOVANJA (SIFRA_KRITERIJUMA);

ALTER TABLE NARUDZBENICA
    ADD CONSTRAINT FK_NARUDZB_NARUCENO_OD FOREIGN KEY (SIFRA_DOBAVLJACA)
    REFERENCES DOBAVLJAC (SIFRA_DOBAVLJACA);

ALTER TABLE STAVKA_NARUDZBENICE
    ADD CONSTRAINT FK_STNARUD_NARUDZBENICA FOREIGN KEY (BROJ_NARUDZBENICE)
    REFERENCES NARUDZBENICA (BROJ_NARUDZBENICE);

ALTER TABLE PRIJEMNICA
    ADD CONSTRAINT FK_PRIJEMN_PRACENA FOREIGN KEY (BROJ_NARUDZBENICE)
    REFERENCES NARUDZBENICA (BROJ_NARUDZBENICE);

ALTER TABLE PRIJEMNICA
    ADD CONSTRAINT FK_PRIJEMN_FAKTURISANA FOREIGN KEY (BROJ_FAKTURE)
    REFERENCES FAKTURA (BROJ_FAKTURE);

ALTER TABLE PRIJEM_STAVKE
    ADD CONSTRAINT FK_PRIJSTAV_PRIJEMNICA FOREIGN KEY (BROJ_PRIJEMNICE)
    REFERENCES PRIJEMNICA (BROJ_PRIJEMNICE);

ALTER TABLE PRIJEM_STAVKE
    ADD CONSTRAINT FK_PRIJSTAV_STNARUD FOREIGN KEY (BROJ_NARUDZBENICE, RB_STAVKE)
    REFERENCES STAVKA_NARUDZBENICE (BROJ_NARUDZBENICE, RB_STAVKE);

ALTER TABLE REKLAMACIJA
    ADD CONSTRAINT FK_REKLAMAC_PRIJEMNICA FOREIGN KEY (BROJ_PRIJEMNICE)
    REFERENCES PRIJEMNICA (BROJ_PRIJEMNICE);

ALTER TABLE REKLAMIRANA_STAVKA
    ADD CONSTRAINT FK_REKSTAV_REKLAMACIJA FOREIGN KEY (BROJ_REKLAMACIJE)
    REFERENCES REKLAMACIJA (BROJ_REKLAMACIJE);

ALTER TABLE REKLAMIRANA_STAVKA
    ADD CONSTRAINT FK_REKSTAV_STNARUD FOREIGN KEY (BROJ_NARUDZBENICE, RB_STAVKE)
    REFERENCES STAVKA_NARUDZBENICE (BROJ_NARUDZBENICE, RB_STAVKE);

ALTER TABLE FAKTURA
    ADD CONSTRAINT FK_FAKTURA_IZDATA_PO FOREIGN KEY (BROJ_UGOVORA)
    REFERENCES UGOVOR (BROJ_UGOVORA);

ALTER TABLE STAVKA_FAKTURE
    ADD CONSTRAINT FK_STFAKT_FAKTURA FOREIGN KEY (BROJ_FAKTURE)
    REFERENCES FAKTURA (BROJ_FAKTURE);

ALTER TABLE NALOG_ZA_PLACANJE
    ADD CONSTRAINT FK_NALOG_PLACENA FOREIGN KEY (BROJ_FAKTURE)
    REFERENCES FAKTURA (BROJ_FAKTURE);

