# -*- coding: utf-8 -*-
"""SQL upita za osam izveštaja iz Specifikacije izveštaja.

Svi upiti nose prefiks qIzv, pa se ne mešaju sa upitima koji već postoje
u bazi (qryProgramskaSema, qryKarticaOpreme, Izvestaj1, ...).
Srpska slova su zapisana markerima (~c, ~k, ~s, ~z, ~d) - VBA funkcija T()
ih sastavlja pri kreiranju upita.
"""

def frm(baza, spojevi):
    """FROM klauzula sa ispravnim brojem zagrada (Jet zahteva n-1 para)."""
    n = len(spojevi)
    s = '(' * (n - 1) + baza
    for i, (tip, tabela, alias, on) in enumerate(spojevi):
        s += '\n %s %s AS %s ON %s' % (tip, tabela, alias, on)
        if i < n - 1:
            s += ')'
    return s

I = 'INNER JOIN'
L = 'LEFT JOIN'

# ---------------------------------------------------------------- izvestaj 1
Q1 = """SELECT PS.SIFRA_SEME, PS.NAZIV_SEME, PS.SEZONA, PS.VERZIJA_SEME, PS.STATUS_SEME,
 PS.DATUM_OD AS SEMA_OD, PS.DATUM_DO AS SEMA_DO, PS.DATUM_USVAJANJA,
 (Z.PREZIME & " " & Z.IME) AS UREDNIK_NAZIV, UR.REDAKCIJA,
 PC.RB_CELINE, PC.NAZIV_CELINE, PC.TIP_CELINE, PC.DATUM AS DATUM_CELINE,
 PC.VREME_OD, PC.VREME_DO,
 (PS.SIFRA_SEME & "-" & Format(PC.RB_CELINE,"000")) AS CELINA_KLJUC,
 TE.SIFRA_TERMINA, TE.DATUM AS DATUM_TERMINA, TE.VREME_POCETKA,
 E.NAZIV_EMISIJE, E.ZANR, TE.TRAJANJE_TERMINA, TE.TIP_TERMINA,
 TE.ZONA_GLEDANOSTI, TE.REDNI_BROJ_REPRIZE, TE.STATUS_TERMINA
FROM %s
ORDER BY PS.SIFRA_SEME, PC.RB_CELINE, TE.VREME_POCETKA;""" % frm('PROGRAMSKA_SEMA AS PS', [
 (I, 'PROGRAMSKA_CELINA', 'PC', 'PS.SIFRA_SEME = PC.SIFRA_SEME'),
 (I, 'TERMIN_EMITOVANJA', 'TE',
  '(PC.SIFRA_SEME = TE.SIFRA_SEME) AND (PC.RB_CELINE = TE.RB_CELINE)'),
 (I, 'EMISIJA', 'E', 'TE.SIFRA_EMISIJE = E.SIFRA_EMISIJE'),
 (I, 'UREDNIK', 'UR', 'PS.SIFRA_UREDNIKA = UR.SIFRA_ZAPOSLENOG'),
 (I, 'ZAPOSLENI', 'Z', 'UR.SIFRA_ZAPOSLENOG = Z.SIFRA_ZAPOSLENOG')])

# ---------------------------------------------------------------- izvestaj 2
Q2 = """PARAMETERS [Datum od:] DateTime, [Datum do:] DateTime;
SELECT TE.DATUM, ZE.RB_EMITOVANJA, ZE.STVARNO_VREME_POCETKA,
 E.NAZIV_EMISIJE, MS.NAZIV_SADRZAJA, TE.TRAJANJE_TERMINA, ZE.STVARNO_TRAJANJE,
 (Nz(ZE.STVARNO_TRAJANJE,0) - Nz(TE.TRAJANJE_TERMINA,0)) AS ODSTUPANJE,
 ZE.STATUS_REALIZACIJE, PK.BROJ_LICENCE, PK.VRSTA_PRAVA,
 ZE.OPERATER_EMITOVANJA, ZE.NAPOMENA_O_SMETNJAMA,
 IIf(Len(Nz(ZE.NAPOMENA_O_SMETNJAMA,"")) > 0, 1, 0) AS IMA_SMETNJU,
 [Datum od:] AS PAR_OD, [Datum do:] AS PAR_DO
FROM %s
WHERE TE.DATUM BETWEEN [Datum od:] AND [Datum do:]
ORDER BY TE.DATUM, ZE.STVARNO_VREME_POCETKA;""" % frm('ZAPIS_O_EMITOVANJU AS ZE', [
 (I, 'TERMIN_EMITOVANJA', 'TE', 'ZE.SIFRA_TERMINA = TE.SIFRA_TERMINA'),
 (I, 'EMISIJA', 'E', 'TE.SIFRA_EMISIJE = E.SIFRA_EMISIJE'),
 (I, 'MEDIJSKI_SADRZAJ', 'MS', 'ZE.SIFRA_SADRZAJA = MS.SIFRA_SADRZAJA'),
 (L, 'POKRIVENOST_PRAVOM', 'PP', 'MS.SIFRA_SADRZAJA = PP.SIFRA_SADRZAJA'),
 (L, 'PRAVO_KORISCENJA', 'PK', 'PP.BROJ_LICENCE = PK.BROJ_LICENCE')])

# ---------------------------------------------------------------- izvestaj 3
Q3T = """SELECT E.NAZIV_EMISIJE, E.ZANR, Count(ME.SIFRA_MERENJA) AS BROJ_MERENJA,
 Round(Avg(ME.OSTVARENI_RATING),2) AS PROSECAN_REJTING,
 Round(Avg(ME.UDEO_U_TERMINU),2) AS PROSECAN_UDEO,
 Round(Avg(MG.BROJ_GLEDALACA),0) AS PROSECAN_BROJ_GLEDALACA,
 Round(Avg(MG.PROSECNO_GLEDANJE),1) AS PROSECNO_GLEDANJE
FROM %s
GROUP BY E.NAZIV_EMISIJE, E.ZANR
ORDER BY Avg(ME.OSTVARENI_RATING) DESC;""" % frm('EMISIJA AS E', [
 (I, 'MERENJE_EMISIJE', 'ME', 'E.SIFRA_EMISIJE = ME.SIFRA_EMISIJE'),
 (I, 'MERENJE_GLEDANOSTI', 'MG', 'ME.SIFRA_MERENJA = MG.SIFRA_MERENJA')])

Q3Z = """SELECT E.ZANR, Round(Avg(ME.OSTVARENI_RATING),2) AS PROSECAN_REJTING
FROM EMISIJA AS E INNER JOIN MERENJE_EMISIJE AS ME
 ON E.SIFRA_EMISIJE = ME.SIFRA_EMISIJE
GROUP BY E.ZANR
ORDER BY E.ZANR;"""

Q3D = """SELECT MG.DATUM_MERENJA, Round(Avg(ME.OSTVARENI_RATING),2) AS PROSECAN_REJTING
FROM MERENJE_GLEDANOSTI AS MG INNER JOIN MERENJE_EMISIJE AS ME
 ON MG.SIFRA_MERENJA = ME.SIFRA_MERENJA
GROUP BY MG.DATUM_MERENJA
ORDER BY MG.DATUM_MERENJA;"""

# ---------------------------------------------------------------- izvestaj 4
Q4 = """SELECT PP.SIFRA_PROJEKTA, PP.NAZIV_PROJEKTA, PP.VRSTA_PRODUKCIJE,
 PP.STATUS_PROJEKTA, PP.DATUM_POCETKA, PP.DATUM_ZAVRSETKA, PP.ODOBREN_BUDZET,
 (Z.PREZIME & " " & Z.IME) AS UREDNIK_NAZIV, E.NAZIV_EMISIJE,
 AP.RB_AKTIVNOSTI, AP.NAZIV_AKTIVNOSTI, AP.VRSTA_AKTIVNOSTI,
 AP.LOKACIJA_SNIMANJA, AP.DATUM_OD, AP.DATUM_DO, AP.STATUS_AKTIVNOSTI,
 (PP.SIFRA_PROJEKTA & "-" & Format(AP.RB_AKTIVNOSTI,"000")) AS AKT_KLJUC,
 TP.RB_TROSKA, TP.VRSTA_TROSKA, TP.OPIS_TROSKA, TP.DATUM_NASTANKA,
 TP.IZNOS, TP.BROJ_FAKTURE, FA.STATUS_PLACANJA
FROM %s
ORDER BY PP.SIFRA_PROJEKTA, AP.RB_AKTIVNOSTI, TP.RB_TROSKA;""" % frm('PROJEKAT_PRODUKCIJE AS PP', [
 (I, 'AKTIVNOST_PRODUKCIJE', 'AP', 'PP.SIFRA_PROJEKTA = AP.SIFRA_PROJEKTA'),
 (I, 'ZAPOSLENI', 'Z', 'PP.SIFRA_UREDNIKA = Z.SIFRA_ZAPOSLENOG'),
 (L, 'EMISIJA', 'E', 'PP.SIFRA_EMISIJE = E.SIFRA_EMISIJE'),
 (L, 'TROSAK_PRODUKCIJE', 'TP',
  '(AP.SIFRA_PROJEKTA = TP.SIFRA_PROJEKTA) AND (AP.RB_AKTIVNOSTI = TP.RB_AKTIVNOSTI)'),
 (L, 'FAKTURA', 'FA', 'TP.BROJ_FAKTURE = FA.BROJ_FAKTURE')])

# ---------------------------------------------------------------- izvestaj 5
Q5A = """SELECT Z.SIFRA_ZAPOSLENOG, Z.IME, Z.PREZIME, Z.RADNO_MESTO,
 OJ.NAZIV_JEDINICE,
 (Z.PREZIME & " " & Z.IME & " (" & Z.SIFRA_ZAPOSLENOG & ")") AS ZAPOSLENI_KLJUC,
 PP.SIFRA_PROJEKTA, PP.NAZIV_PROJEKTA, AP.RB_AKTIVNOSTI, AP.NAZIV_AKTIVNOSTI,
 AN.ULOGA_NA_SNIMANJU, AN.DATUM_OD, AN.DATUM_DO, AN.BROJ_ANGAZOVANIH_SATI
FROM %s
ORDER BY Z.PREZIME, Z.IME, AN.DATUM_OD;""" % frm('ANGAZOVANJE_NA_AKTIVNOSTI AS AN', [
 (I, 'ZAPOSLENI', 'Z', 'AN.SIFRA_ZAPOSLENOG = Z.SIFRA_ZAPOSLENOG'),
 (I, 'ORGANIZACIONA_JEDINICA', 'OJ', 'Z.SIFRA_JEDINICE = OJ.SIFRA_JEDINICE'),
 (I, 'AKTIVNOST_PRODUKCIJE', 'AP',
  '(AN.SIFRA_PROJEKTA = AP.SIFRA_PROJEKTA) AND (AN.RB_AKTIVNOSTI = AP.RB_AKTIVNOSTI)'),
 (I, 'PROJEKAT_PRODUKCIJE', 'PP', 'AP.SIFRA_PROJEKTA = PP.SIFRA_PROJEKTA')])

Q5O = """SELECT O.INVENTARSKI_BROJ, O.NAZIV_OPREME, O.MODEL_OPREME, O.STATUS_OPREME,
 PP.NAZIV_PROJEKTA, AP.RB_AKTIVNOSTI, AP.NAZIV_AKTIVNOSTI,
 RO.DATUM_REZERVACIJE, RO.TRAJANJE_ZADUZENJA
FROM %s
ORDER BY O.INVENTARSKI_BROJ, RO.DATUM_REZERVACIJE;""" % frm('REZERVACIJA_OPREME AS RO', [
 (I, 'OPREMA', 'O', 'RO.INVENTARSKI_BROJ = O.INVENTARSKI_BROJ'),
 (I, 'AKTIVNOST_PRODUKCIJE', 'AP',
  '(RO.SIFRA_PROJEKTA = AP.SIFRA_PROJEKTA) AND (RO.RB_AKTIVNOSTI = AP.RB_AKTIVNOSTI)'),
 (I, 'PROJEKAT_PRODUKCIJE', 'PP', 'AP.SIFRA_PROJEKTA = PP.SIFRA_PROJEKTA')])

# ---------------------------------------------------------------- izvestaj 6
Q6F = """SELECT F.BROJ_UGOVORA, Sum(F.IZNOS_ZA_PLACANJE) AS FAKTURISANO,
 Count(F.BROJ_FAKTURE) AS BROJ_FAKTURA, Min(F.STATUS_PLACANJA) AS STATUS_FAKTURE
FROM FAKTURA AS F
WHERE F.BROJ_UGOVORA Is Not Null
GROUP BY F.BROJ_UGOVORA;"""

Q6 = """PARAMETERS [~Sifra ili naziv ogla~siva~ca:] Text ( 255 );
SELECT K.SIFRA_KLIJENTA, K.NAZIV_KLIJENTA, K.PIB, K.KONTAKT_OSOBA, K.GRAD,
 OG.BRANSA, OG.GODISNJI_BUDZET,
 U.BROJ_UGOVORA, U.DATUM_SKLAPANJA, U.VAZI_OD, U.VAZI_DO, U.STATUS_UGOVORA,
 U.UKUPNA_VREDNOST, UO.UGOVORENI_TERMINI,
 SU.RB_STAVKE, SU.OPIS_STAVKE, SU.KOLICINA_SEKUNDE, SU.JEDINICNA_CENA,
 SU.POPUST, SU.VREDNOST_STAVKE,
 (U.BROJ_UGOVORA & "-" & Format(SU.RB_STAVKE,"000")) AS STAVKA_KLJUC,
 ER.DATUM_EMITOVANJA, ER.VREME_EMITOVANJA, ER.SIFRA_BLOKA, RB.SIFRA_TERMINA,
 CN.ZONA, ER.TRAJANJE_SPOTA, ER.NAPLACENI_IZNOS, ER.STATUS_NAPLATE,
 (SELECT Sum(S2.KOLICINA_SEKUNDE) FROM STAVKA_UGOVORA AS S2
  WHERE S2.BROJ_UGOVORA = U.BROJ_UGOVORA) AS UGOVORENO_SEKUNDI,
 (SELECT Sum(S2.VREDNOST_STAVKE) FROM STAVKA_UGOVORA AS S2
  WHERE S2.BROJ_UGOVORA = U.BROJ_UGOVORA) AS UGOVORENA_VREDNOST,
 FK.FAKTURISANO, FK.STATUS_FAKTURE
FROM %s
WHERE K.SIFRA_KLIJENTA = [~Sifra ili naziv ogla~siva~ca:]
 OR K.NAZIV_KLIJENTA LIKE "*" & [~Sifra ili naziv ogla~siva~ca:] & "*"
ORDER BY U.BROJ_UGOVORA, SU.RB_STAVKE, ER.DATUM_EMITOVANJA;""" % frm('KLIJENT AS K', [
 (I, 'OGLASIVAC', 'OG', 'K.SIFRA_KLIJENTA = OG.SIFRA_KLIJENTA'),
 (I, 'UGOVOR', 'U', 'K.SIFRA_KLIJENTA = U.SIFRA_KLIJENTA'),
 (I, 'UGOVOR_O_OGLASAVANJU', 'UO', 'U.BROJ_UGOVORA = UO.BROJ_UGOVORA'),
 (I, 'STAVKA_UGOVORA', 'SU', 'U.BROJ_UGOVORA = SU.BROJ_UGOVORA'),
 (L, 'EMITOVANJE_REKLAME', 'ER',
  '(SU.BROJ_UGOVORA = ER.BROJ_UGOVORA) AND (SU.RB_STAVKE = ER.RB_STAVKE_UGOVORA)'),
 (L, 'REKLAMNI_BLOK', 'RB', 'ER.SIFRA_BLOKA = RB.SIFRA_BLOKA'),
 (L, 'CENOVNIK_REKL_TERMINA', 'CN', 'RB.SIFRA_CENOVNIKA = CN.SIFRA_CENOVNIKA'),
 (L, '[qIzv6_Fakture]', 'FK', 'U.BROJ_UGOVORA = FK.BROJ_UGOVORA')])

# ---------------------------------------------------------------- izvestaj 7
Q7Z = """SELECT Z.SIFRA_PLANA, Z.BROJ_ZAHTEVA, Z.DATUM_ZAHTEVA, Z.VRSTA_NABAVKE,
 Z.STATUS_ZAHTEVA, Z.PRIORITET, Z.PROCENJENA_VREDNOST
FROM ZAHTEV_ZA_NABAVKU AS Z
WHERE Z.SIFRA_PLANA Is Not Null
 AND Z.BROJ_ZAHTEVA = (SELECT Min(Z2.BROJ_ZAHTEVA) FROM ZAHTEV_ZA_NABAVKU AS Z2
  WHERE Z2.SIFRA_PLANA = Z.SIFRA_PLANA);"""

Q7N = """SELECT N.SIFRA_DOBAVLJACA, Min(N.BROJ_NARUDZBENICE) AS BROJ_NARUDZBENICE,
 Sum(N.UKUPAN_IZNOS) AS IZNOS_NARUDZBENICA,
 Count(N.BROJ_NARUDZBENICE) AS BROJ_NARUDZBENICA
FROM NARUDZBENICA AS N
GROUP BY N.SIFRA_DOBAVLJACA;"""

Q7I = """SELECT PS.SIFRA_PLANA, PS.RB_STAVKE, Min(PD.BROJ_PONUDE) AS BROJ_PONUDE,
 Min(PD.SIFRA_DOBAVLJACA) AS SIFRA_DOBAVLJACA,
 Min(PS.PONUDJENA_CENA) AS PONUDJENA_CENA
FROM PONUDJENA_STAVKA AS PS INNER JOIN PONUDA_DOBAVLJACA AS PD
 ON PS.BROJ_PONUDE = PD.BROJ_PONUDE
WHERE PD.STATUS_PONUDE = "Izabrana"
GROUP BY PS.SIFRA_PLANA, PS.RB_STAVKE;"""

Q7 = """SELECT PN.SIFRA_PLANA, PN.GODINA_PLANA, PN.DATUM_DONOSENJA, PN.STATUS_PLANA,
 PN.DONOSILAC_PLANA, PN.UKUPNA_VREDNOST,
 SP.RB_STAVKE, SP.OPIS_ARTIKLA, SP.KOLICINA, SP.JEDINICA_MERE,
 SP.PROCENJENA_CENA, SP.PLANIRANI_KVARTAL,
 ZH.BROJ_ZAHTEVA, ZH.STATUS_ZAHTEVA, ZH.PRIORITET,
 IZ.BROJ_PONUDE AS IZABRANA_PONUDA, IZ.PONUDJENA_CENA, D.NAZIV_DOBAVLJACA,
 NB.BROJ_NARUDZBENICE, NB.IZNOS_NARUDZBENICA,
 (Nz(NB.IZNOS_NARUDZBENICA,0) - Nz(SP.PROCENJENA_CENA,0)) AS ODSTUPANJE
FROM %s
ORDER BY PN.SIFRA_PLANA, SP.RB_STAVKE;""" % frm('PLAN_NABAVKE AS PN', [
 (I, 'STAVKA_PLANA_NABAVKE', 'SP', 'PN.SIFRA_PLANA = SP.SIFRA_PLANA'),
 (L, '[qIzv7_Zahtev]', 'ZH', 'PN.SIFRA_PLANA = ZH.SIFRA_PLANA'),
 (L, '[qIzv7_Izabrana]', 'IZ',
  '(SP.SIFRA_PLANA = IZ.SIFRA_PLANA) AND (SP.RB_STAVKE = IZ.RB_STAVKE)'),
 (L, 'DOBAVLJAC', 'D', 'IZ.SIFRA_DOBAVLJACA = D.SIFRA_DOBAVLJACA'),
 (L, '[qIzv7_Narudzbe]', 'NB', 'IZ.SIFRA_DOBAVLJACA = NB.SIFRA_DOBAVLJACA')])

Q7P = """SELECT PS.SIFRA_PLANA, PS.RB_STAVKE, PD.BROJ_PONUDE, D.NAZIV_DOBAVLJACA,
 PD.DATUM_PRIJEMA, PD.UKUPNA_CENA, PS.PONUDJENA_CENA, PD.ROK_ISPORUKE,
 PD.USLOVI_PLACANJA, PD.UKUPNO_BODOVA, PD.STATUS_PONUDE,
 (PS.SIFRA_PLANA & "-" & Format(PS.RB_STAVKE,"000") & "-" & PD.BROJ_PONUDE)
  AS PONUDA_KLJUC,
 KV.NAZIV_KRITERIJUMA, KV.NACIN_BODOVANJA, OP.BROJ_BODOVA, OP.KOMENTAR_OCENE
FROM %s
ORDER BY PS.SIFRA_PLANA, PS.RB_STAVKE, PD.BROJ_PONUDE, KV.NAZIV_KRITERIJUMA;""" % frm(
 'PONUDJENA_STAVKA AS PS', [
 (I, 'PONUDA_DOBAVLJACA', 'PD', 'PS.BROJ_PONUDE = PD.BROJ_PONUDE'),
 (I, 'DOBAVLJAC', 'D', 'PD.SIFRA_DOBAVLJACA = D.SIFRA_DOBAVLJACA'),
 (L, 'OCENA_PONUDE', 'OP', 'PD.BROJ_PONUDE = OP.BROJ_PONUDE'),
 (L, 'KRITERIJUM_VREDNOVANJA', 'KV', 'OP.SIFRA_KRITERIJUMA = KV.SIFRA_KRITERIJUMA')])

# ---------------------------------------------------------------- izvestaj 8
_ISTICE = ('PK.DATUM_DO < Date() OR Nz(PK.ISKORISCENO_EMITOVANJA,0) >='
           ' Nz(PK.DOZVOLJENO_EMITOVANJA,0) OR DateDiff("d", Date(), PK.DATUM_DO) <= 30')

Q8 = """SELECT PK.BROJ_LICENCE, PK.VRSTA_PRAVA, PK.NOSILAC_PRAVA, PK.TERITORIJA,
 PK.DATUM_OD, PK.DATUM_DO, DateDiff("d", Date(), PK.DATUM_DO) AS DANA_DO_ISTEKA,
 PK.DOZVOLJENO_EMITOVANJA, PK.ISKORISCENO_EMITOVANJA,
 (Nz(PK.DOZVOLJENO_EMITOVANJA,0) - Nz(PK.ISKORISCENO_EMITOVANJA,0))
  AS PREOSTALO_EMITOVANJA,
 IIf(PK.DATUM_DO < Date(), "Isteklo",
  IIf(Nz(PK.ISKORISCENO_EMITOVANJA,0) >= Nz(PK.DOZVOLJENO_EMITOVANJA,0),
   "Iskori~s~ceno",
   IIf(DateDiff("d", Date(), PK.DATUM_DO) <= 30, "Uskoro isti~ce", "Va~ze~ce")))
  AS STATUS_PRAVA,
 IIf(%(u)s, 0, 1) AS PRIORITET_STATUSA,
 IIf(%(u)s, "1. Prava kojima je rok istekao, uskoro isti~ce ili je iskori~s~cen"
  & " dozvoljen broj emitovanja", "2. Va~ze~ca prava") AS GRUPA_STATUSA,
 (Format(PK.DATUM_DO,"yyyymmdd") & "-" & PK.BROJ_LICENCE) AS LICENCA_KLJUC,
 MS.SIFRA_SADRZAJA, MS.NAZIV_SADRZAJA, MS.FORMAT_ZAPISA, PP.OBLAST_POKRIVENOSTI,
 NS.ZEMLJA_POREKLA, UN.BROJ_UGOVORA AS UGOVOR_NABAVKE,
 (SELECT Count(*) FROM ZAPIS_O_EMITOVANJU AS ZE
  WHERE ZE.SIFRA_SADRZAJA = MS.SIFRA_SADRZAJA) AS BROJ_EMITOVANJA
FROM %(f)s
ORDER BY IIf(%(u)s, 0, 1), PK.DATUM_DO, PK.BROJ_LICENCE, MS.NAZIV_SADRZAJA;""" % dict(
 u=_ISTICE, f=frm('PRAVO_KORISCENJA AS PK', [
 (L, 'POKRIVENOST_PRAVOM', 'PP', 'PK.BROJ_LICENCE = PP.BROJ_LICENCE'),
 (L, 'MEDIJSKI_SADRZAJ', 'MS', 'PP.SIFRA_SADRZAJA = MS.SIFRA_SADRZAJA'),
 (L, 'NABAVLJENI_SADRZAJ', 'NS', 'MS.SIFRA_SADRZAJA = NS.SIFRA_SADRZAJA'),
 (L, 'UGOVOR_O_NABAVCI', 'UN', 'NS.BROJ_UGOVORA = UN.BROJ_UGOVORA')]))

# redosled je vazan: pomocni upiti se prave pre onih koji ih koriste
U = [
 ('qIzv1_Sema', Q1),
 ('qIzv2_Playout', Q2),
 ('qIzv3_Emisije', Q3T),
 ('qIzv3_RejtingPoZanru', Q3Z),
 ('qIzv3_RejtingPoDatumu', Q3D),
 ('qIzv4_Troskovi', Q4),
 ('qIzv5_Angazovanje', Q5A),
 ('qIzv5_Oprema', Q5O),
 ('qIzv6_Fakture', Q6F),
 ('qIzv6_Kartica', Q6),
 ('qIzv7_Zahtev', Q7Z),
 ('qIzv7_Narudzbe', Q7N),
 ('qIzv7_Izabrana', Q7I),
 ('qIzv7_Stavke', Q7),
 ('qIzv7_Ponude', Q7P),
 ('qIzv8_Prava', Q8),
]
