# -*- coding: utf-8 -*-
"""SQL upita (Access/Jet sintaksa).  Imena se poklapaju sa prilogom u
Specifikaciji izvestaja."""

U = [
('qryProgramskaSema', """
SELECT PS.NAZIV_SEME, PS.SEZONA, PC.RB_CELINE, PC.NAZIV_CELINE, PC.TIP_CELINE,
 PC.DATUM AS DATUM_CELINE, TE.VREME_POCETKA, E.NAZIV_EMISIJE, E.ZANR,
 TE.TRAJANJE_TERMINA, TE.TIP_TERMINA, TE.ZONA_GLEDANOSTI, TE.REDNI_BROJ_REPRIZE,
 TE.STATUS_TERMINA
FROM ((PROGRAMSKA_SEMA AS PS
 INNER JOIN PROGRAMSKA_CELINA AS PC ON PS.SIFRA_SEME = PC.SIFRA_SEME)
 INNER JOIN TERMIN_EMITOVANJA AS TE ON (PC.SIFRA_SEME = TE.SIFRA_SEME)
  AND (PC.RB_CELINE = TE.RB_CELINE))
 INNER JOIN EMISIJA AS E ON TE.SIFRA_EMISIJE = E.SIFRA_EMISIJE
ORDER BY PC.RB_CELINE, TE.DATUM, TE.VREME_POCETKA;"""),

('qryPlayoutLog', """
PARAMETERS [Unesite datum od:] DateTime, [Unesite datum do:] DateTime;
SELECT TE.DATUM, ZE.STVARNO_VREME_POCETKA, E.NAZIV_EMISIJE, MS.NAZIV_SADRZAJA,
 TE.TRAJANJE_TERMINA, ZE.STVARNO_TRAJANJE,
 (ZE.STVARNO_TRAJANJE - TE.TRAJANJE_TERMINA) AS ODSTUPANJE,
 ZE.STATUS_REALIZACIJE, PK.BROJ_LICENCE, PK.VRSTA_PRAVA,
 ZE.OPERATER_EMITOVANJA, ZE.NAPOMENA_O_SMETNJAMA
FROM ((((ZAPIS_O_EMITOVANJU AS ZE
 INNER JOIN TERMIN_EMITOVANJA AS TE ON ZE.SIFRA_TERMINA = TE.SIFRA_TERMINA)
 INNER JOIN EMISIJA AS E ON TE.SIFRA_EMISIJE = E.SIFRA_EMISIJE)
 INNER JOIN MEDIJSKI_SADRZAJ AS MS ON ZE.SIFRA_SADRZAJA = MS.SIFRA_SADRZAJA)
 LEFT JOIN POKRIVENOST_PRAVOM AS PP ON MS.SIFRA_SADRZAJA = PP.SIFRA_SADRZAJA)
 LEFT JOIN PRAVO_KORISCENJA AS PK ON PP.BROJ_LICENCE = PK.BROJ_LICENCE
WHERE TE.DATUM BETWEEN [Unesite datum od:] AND [Unesite datum do:]
ORDER BY TE.DATUM, ZE.STVARNO_VREME_POCETKA;"""),

('qryGledanostPoZanru', """
SELECT E.ZANR, Round(Avg(ME.OSTVARENI_RATING),2) AS PROSECAN_REJTING
FROM EMISIJA AS E INNER JOIN MERENJE_EMISIJE AS ME
 ON E.SIFRA_EMISIJE = ME.SIFRA_EMISIJE
GROUP BY E.ZANR
ORDER BY Avg(ME.OSTVARENI_RATING) DESC;"""),

('qryGledanostEmisija', """
SELECT E.NAZIV_EMISIJE, E.ZANR, Count(ME.SIFRA_MERENJA) AS BROJ_MERENJA,
 Round(Avg(ME.OSTVARENI_RATING),2) AS PROSECAN_REJTING,
 Round(Avg(ME.UDEO_U_TERMINU),2) AS PROSECAN_UDEO,
 Round(Avg(MG.BROJ_GLEDALACA),0) AS PROSECAN_BROJ_GLEDALACA,
 Round(Avg(MG.PROSECNO_GLEDANJE),0) AS PROSECNO_GLEDANJE
FROM (EMISIJA AS E INNER JOIN MERENJE_EMISIJE AS ME
 ON E.SIFRA_EMISIJE = ME.SIFRA_EMISIJE)
 INNER JOIN MERENJE_GLEDANOSTI AS MG ON ME.SIFRA_MERENJA = MG.SIFRA_MERENJA
GROUP BY E.NAZIV_EMISIJE, E.ZANR
ORDER BY Avg(ME.OSTVARENI_RATING) DESC;"""),

('qryTroskoviProjekta', """
SELECT PP.SIFRA_PROJEKTA, PP.NAZIV_PROJEKTA, PP.VRSTA_PRODUKCIJE,
 PP.ODOBREN_BUDZET, PP.STATUS_PROJEKTA, AP.RB_AKTIVNOSTI, AP.NAZIV_AKTIVNOSTI,
 AP.VRSTA_AKTIVNOSTI, AP.LOKACIJA_SNIMANJA, AP.STATUS_AKTIVNOSTI,
 TP.RB_TROSKA, TP.VRSTA_TROSKA, TP.OPIS_TROSKA, TP.DATUM_NASTANKA,
 TP.IZNOS, TP.BROJ_FAKTURE
FROM (PROJEKAT_PRODUKCIJE AS PP
 INNER JOIN AKTIVNOST_PRODUKCIJE AS AP ON PP.SIFRA_PROJEKTA = AP.SIFRA_PROJEKTA)
 LEFT JOIN TROSAK_PRODUKCIJE AS TP ON (AP.SIFRA_PROJEKTA = TP.SIFRA_PROJEKTA)
  AND (AP.RB_AKTIVNOSTI = TP.RB_AKTIVNOSTI)
ORDER BY PP.SIFRA_PROJEKTA, AP.RB_AKTIVNOSTI, TP.RB_TROSKA;"""),

('qryAngazovanje', """
SELECT Z.PREZIME & " " & Z.IME AS ZAPOSLENI_NAZIV, Z.RADNO_MESTO,
 PP.NAZIV_PROJEKTA, AP.NAZIV_AKTIVNOSTI, AN.ULOGA_NA_SNIMANJU,
 AN.DATUM_OD, AN.DATUM_DO, AN.BROJ_ANGAZOVANIH_SATI
FROM ((ANGAZOVANJE_NA_AKTIVNOSTI AS AN
 INNER JOIN ZAPOSLENI AS Z ON AN.SIFRA_ZAPOSLENOG = Z.SIFRA_ZAPOSLENOG)
 INNER JOIN AKTIVNOST_PRODUKCIJE AS AP ON (AN.SIFRA_PROJEKTA = AP.SIFRA_PROJEKTA)
  AND (AN.RB_AKTIVNOSTI = AP.RB_AKTIVNOSTI))
 INNER JOIN PROJEKAT_PRODUKCIJE AS PP ON AP.SIFRA_PROJEKTA = PP.SIFRA_PROJEKTA
ORDER BY Z.PREZIME, Z.IME, AN.DATUM_OD;"""),

('qryZaduzenjeOpreme', """
SELECT O.INVENTARSKI_BROJ, O.NAZIV_OPREME, O.MODEL_OPREME,
 PP.NAZIV_PROJEKTA, AP.NAZIV_AKTIVNOSTI, RO.DATUM_REZERVACIJE,
 RO.TRAJANJE_ZADUZENJA
FROM ((REZERVACIJA_OPREME AS RO
 INNER JOIN OPREMA AS O ON RO.INVENTARSKI_BROJ = O.INVENTARSKI_BROJ)
 INNER JOIN AKTIVNOST_PRODUKCIJE AS AP ON (RO.SIFRA_PROJEKTA = AP.SIFRA_PROJEKTA)
  AND (RO.RB_AKTIVNOSTI = AP.RB_AKTIVNOSTI))
 INNER JOIN PROJEKAT_PRODUKCIJE AS PP ON AP.SIFRA_PROJEKTA = PP.SIFRA_PROJEKTA
ORDER BY O.INVENTARSKI_BROJ, RO.DATUM_REZERVACIJE;"""),

('qryKarticaOglasivaca', """
PARAMETERS [Unesite ~sifru ogla~siva~ca:] Text ( 255 );
SELECT K.SIFRA_KLIJENTA, K.NAZIV_KLIJENTA, K.PIB, K.KONTAKT_OSOBA, OG.BRANSA,
 U.BROJ_UGOVORA, U.DATUM_SKLAPANJA, U.VAZI_OD, U.VAZI_DO, U.STATUS_UGOVORA,
 SU.RB_STAVKE, SU.OPIS_STAVKE, SU.KOLICINA_SEKUNDE, SU.JEDINICNA_CENA,
 SU.POPUST, SU.VREDNOST_STAVKE, ER.DATUM_EMITOVANJA, ER.VREME_EMITOVANJA,
 ER.SIFRA_BLOKA, ER.TRAJANJE_SPOTA, ER.NAPLACENI_IZNOS, ER.STATUS_NAPLATE
FROM ((((KLIJENT AS K
 INNER JOIN OGLASIVAC AS OG ON K.SIFRA_KLIJENTA = OG.SIFRA_KLIJENTA)
 INNER JOIN UGOVOR AS U ON K.SIFRA_KLIJENTA = U.SIFRA_KLIJENTA)
 INNER JOIN UGOVOR_O_OGLASAVANJU AS UO ON U.BROJ_UGOVORA = UO.BROJ_UGOVORA)
 INNER JOIN STAVKA_UGOVORA AS SU ON U.BROJ_UGOVORA = SU.BROJ_UGOVORA)
 LEFT JOIN EMITOVANJE_REKLAME AS ER ON (SU.BROJ_UGOVORA = ER.BROJ_UGOVORA)
  AND (SU.RB_STAVKE = ER.RB_STAVKE_UGOVORA)
WHERE K.SIFRA_KLIJENTA = [Unesite ~sifru ogla~siva~ca:]
ORDER BY U.BROJ_UGOVORA, SU.RB_STAVKE, ER.DATUM_EMITOVANJA;"""),

('qryPlanNabavke', """
SELECT PN.SIFRA_PLANA, PN.GODINA_PLANA, SP.RB_STAVKE, SP.OPIS_ARTIKLA,
 SP.KOLICINA, SP.JEDINICA_MERE, SP.PROCENJENA_CENA, SP.PLANIRANI_KVARTAL,
 ZN.BROJ_ZAHTEVA, ZN.STATUS_ZAHTEVA, NR.BROJ_NARUDZBENICE, NR.UKUPAN_IZNOS,
 (Nz(NR.UKUPAN_IZNOS,0) - SP.PROCENJENA_CENA) AS ODSTUPANJE
FROM (((PLAN_NABAVKE AS PN
 INNER JOIN STAVKA_PLANA_NABAVKE AS SP ON PN.SIFRA_PLANA = SP.SIFRA_PLANA)
 LEFT JOIN ZAHTEV_ZA_NABAVKU AS ZN ON PN.SIFRA_PLANA = ZN.SIFRA_PLANA)
 LEFT JOIN PONUDJENA_STAVKA AS PS ON (SP.SIFRA_PLANA = PS.SIFRA_PLANA)
  AND (SP.RB_STAVKE = PS.RB_STAVKE))
 LEFT JOIN (PONUDA_DOBAVLJACA AS PD
  INNER JOIN NARUDZBENICA AS NR ON PD.SIFRA_DOBAVLJACA = NR.SIFRA_DOBAVLJACA)
  ON PS.BROJ_PONUDE = PD.BROJ_PONUDE AND PD.STATUS_PONUDE = "Izabrana"
ORDER BY SP.RB_STAVKE;"""),

('qryVrednovanjePonuda', """
SELECT PD.BROJ_PONUDE, D.NAZIV_DOBAVLJACA, PD.UKUPNA_CENA, PD.ROK_ISPORUKE,
 PD.USLOVI_PLACANJA, KV.NAZIV_KRITERIJUMA, OP.BROJ_BODOVA, OP.KOMENTAR_OCENE,
 PD.UKUPNO_BODOVA, PD.STATUS_PONUDE
FROM ((PONUDA_DOBAVLJACA AS PD
 INNER JOIN DOBAVLJAC AS D ON PD.SIFRA_DOBAVLJACA = D.SIFRA_DOBAVLJACA)
 INNER JOIN OCENA_PONUDE AS OP ON PD.BROJ_PONUDE = OP.BROJ_PONUDE)
 INNER JOIN KRITERIJUM_VREDNOVANJA AS KV
  ON OP.SIFRA_KRITERIJUMA = KV.SIFRA_KRITERIJUMA
ORDER BY PD.BROJ_PONUDE, KV.SIFRA_KRITERIJUMA;"""),

('qryPravaKoriscenja', """
SELECT PK.BROJ_LICENCE, PK.VRSTA_PRAVA, PK.NOSILAC_PRAVA, PK.TERITORIJA,
 PK.DATUM_OD, PK.DATUM_DO, DateDiff("d", Date(), PK.DATUM_DO) AS DANA_DO_ISTEKA,
 PK.DOZVOLJENO_EMITOVANJA, PK.ISKORISCENO_EMITOVANJA,
 (PK.DOZVOLJENO_EMITOVANJA - PK.ISKORISCENO_EMITOVANJA) AS PREOSTALO_EMITOVANJA,
 MS.NAZIV_SADRZAJA, PP.OBLAST_POKRIVENOSTI,
 IIf(PK.DATUM_DO < Date(), "Isteklo",
  IIf(PK.ISKORISCENO_EMITOVANJA >= PK.DOZVOLJENO_EMITOVANJA, "Iskori~sceno",
   IIf(DateDiff("d", Date(), PK.DATUM_DO) <= 30, "Uskoro isti~ce", "Va~ze~ce"))) AS STATUS_PRAVA
FROM (PRAVO_KORISCENJA AS PK
 LEFT JOIN POKRIVENOST_PRAVOM AS PP ON PK.BROJ_LICENCE = PP.BROJ_LICENCE)
 LEFT JOIN MEDIJSKI_SADRZAJ AS MS ON PP.SIFRA_SADRZAJA = MS.SIFRA_SADRZAJA
ORDER BY PK.DATUM_DO;"""),

('qryEmisijePregled', """
SELECT E.SIFRA_EMISIJE, E.NAZIV_EMISIJE, E.ZANR, E.PREDVIDJENO_TRAJANJE,
 E.STATUS_EMISIJE
FROM EMISIJA AS E ORDER BY E.NAZIV_EMISIJE;"""),

('qryOglasivaciPregled', """
SELECT K.SIFRA_KLIJENTA, K.NAZIV_KLIJENTA, K.PIB, OG.BRANSA, OG.GODISNJI_BUDZET
FROM KLIJENT AS K INNER JOIN OGLASIVAC AS OG
 ON K.SIFRA_KLIJENTA = OG.SIFRA_KLIJENTA
ORDER BY K.NAZIV_KLIJENTA;"""),
]
