# -*- coding: utf-8 -*-
"""Tematske celine (Subject Areas). Redosled u listi je i redosled u skriptu
i u dijagramu. Sadrzaj se ne menja - samo grupisanje i redosled."""

AREAS = [
 ('Organizacija i kadrovi', [
    'ORGANIZACIONA_JEDINICA', 'ZAPOSLENI', 'UREDNIK', 'NOVINAR_REPORTER',
    'TEHNICKO_OSOBLJE', 'REFERENT', 'SERVISERI']),
 ('Oprema', [
    'OPREMA', 'SNIMATELJSKA_OPREMA', 'STUDIJSKA_I_EMISIONA_OPREMA',
    'AUDIO_OPREMA', 'SVETLOSNA_OPREMA', 'ZADUZENJE_OPREME', 'SERVISIRANJE_OPREME']),
 ('Produkcija', [
    'PROJEKAT_PRODUKCIJE', 'AKTIVNOST_PRODUKCIJE', 'TROSAK_PRODUKCIJE',
    'ANGAZOVANJE_NA_AKTIVNOSTI', 'REZERVACIJA_OPREME', 'SIROVI_SNIMAK',
    'GRAFICKI_I_MUZICKI_ELEMENT']),
 ('Program i emitovanje', [
    'PROGRAMSKA_SEMA', 'PROGRAMSKA_CELINA', 'TERMIN_EMITOVANJA', 'EMISIJA',
    'MEDIJSKI_SADRZAJ', 'PRODUCIRANI_SADRZAJ', 'NABAVLJENI_SADRZAJ',
    'REKLAMNI_SADRZAJ', 'ZAPIS_O_EMITOVANJU', 'MONTAZA_SNIMKA',
    'UGRADNJA_ELEMENTA', 'SADRZAJ_EMISIJE', 'PRAVO_KORISCENJA',
    'POKRIVENOST_PRAVOM', 'POVRATNA_INFO_GLEDALACA', 'MERENJE_GLEDANOSTI',
    'MERENJE_EMISIJE']),
 ('Marketing i prodaja', [
    'CENOVNIK_REKL_TERMINA', 'REKLAMNI_BLOK', 'EMITOVANJE_REKLAME', 'KLIJENT',
    'OGLASIVAC', 'KUPAC_SADRZAJA', 'UGOVOR', 'STAVKA_UGOVORA',
    'UGOVOR_O_OGLASAVANJU', 'UGOVOR_O_PRODAJI_TV_SADRZAJA', 'UGOVOR_O_NABAVCI',
    'USTUPANJE_SADRZAJA']),
 ('Nabavka', [
    'PLAN_NABAVKE', 'ZAHTEV_ZA_NABAVKU', 'STAVKA_PLANA_NABAVKE', 'DOBAVLJAC',
    'DOBAVLJAC_TV_SADRZAJA', 'DOBAVLJAC_OPREME_I_MATERIJALA',
    'PONUDA_DOBAVLJACA', 'PONUDJENA_STAVKA', 'KRITERIJUM_VREDNOVANJA',
    'OCENA_PONUDE', 'NARUDZBENICA', 'STAVKA_NARUDZBENICE', 'PRIJEMNICA',
    'PRIJEM_STAVKE', 'REKLAMACIJA', 'REKLAMIRANA_STAVKA']),
 ('Finansije', ['FAKTURA', 'STAVKA_FAKTURE', 'NALOG_ZA_PLACANJE']),
]

ORDER = [t for _, ts in AREAS for t in ts]
AREA_OF = {t: a for a, ts in AREAS for t in ts}
