# -*- coding: utf-8 -*-
"""Unija rezervisanih reci: ANSI SQL-92/99/2003, SQL Server, Oracle, DB2, ODBC,
plus reci koje ERwin-ov parser skripta tretira kao kljucne (FORMAT, MODEL, LABEL...).
Koristi se da nijedno ime tabele ili kolone ne padne na parsiranju."""

RESERVED = set("""
ABSOLUTE ACCESS ACTION ADD ADMIN AFTER AGGREGATE ALIAS ALL ALLOCATE ALTER ANALYZE AND ANY
ARE ARRAY AS ASC ASSERTION AT AUDIT AUTHORIZATION AVG BACKUP BEFORE BEGIN BETWEEN BIGINT
BINARY BIT BLOB BOOLEAN BOTH BREAK BROWSE BULK BY CALL CASCADE CASCADED CASE CAST CATALOG
CHAR CHARACTER CHECK CHECKPOINT CLASS CLOB CLOSE CLUSTER CLUSTERED COALESCE COLLATE
COLLATION COLUMN COMMENT COMMIT COMPRESS COMPUTE CONNECT CONNECTION CONSTRAINT CONSTRAINTS
CONTAINS CONTINUE CONVERT CORRESPONDING COUNT CREATE CROSS CUBE CURRENT CURRENT_DATE
CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR CYCLE DATA DATABASE DATE DATETIME DAY
DBCC DEALLOCATE DEC DECIMAL DECLARE DEFAULT DEFERRABLE DEFERRED DELETE DENY DEPTH DEREF
DESC DESCRIBE DESCRIPTOR DETERMINISTIC DIAGNOSTICS DICTIONARY DISCONNECT DISK DISTINCT
DISTRIBUTED DOMAIN DOUBLE DROP DUMP DYNAMIC EACH ELSE ELSEIF END EQUALS ERRLVL ESCAPE EVERY
EXCEPT EXCEPTION EXEC EXECUTE EXISTS EXIT EXPLAIN EXTERNAL EXTRACT FALSE FETCH FILE
FILLFACTOR FILTER FIRST FLOAT FOR FORCE FOREIGN FORMAT FOUND FREE FREETEXT FROM FULL
FUNCTION GENERAL GET GLOBAL GO GOTO GRANT GROUP GROUPING HANDLER HAVING HOLD HOLDLOCK HOUR
IDENTITY IDENTITYCOL IF IGNORE IMMEDIATE IN INCREMENT INDEX INDICATOR INITIAL INITIALLY
INNER INOUT INPUT INSENSITIVE INSERT INT INTEGER INTERSECT INTERVAL INTO IS ISOLATION
ITERATE JOIN KEY KILL LABEL LANGUAGE LARGE LAST LATERAL LEADING LEAVE LEFT LESS LEVEL LIKE
LIMIT LINENO LOAD LOCAL LOCALTIME LOCALTIMESTAMP LOCATOR LOCK LONG LOOP LOWER MAP MATCH MAX
MAXEXTENTS MERGE METHOD MIN MINUS MINUTE MLSLABEL MOD MODE MODEL MODIFIES MODIFY MODULE
MONTH NAMES NATIONAL NATURAL NCHAR NCLOB NEW NEXT NO NOAUDIT NOCHECK NOCOMPRESS
NONCLUSTERED NONE NOT NOWAIT NULL NULLIF NUMBER NUMERIC OBJECT OF OFF OFFSETS OLD ON ONLINE
ONLY OPEN OPENDATASOURCE OPENQUERY OPENROWSET OPENXML OPERATION OPTION OR ORDER ORDINALITY
OUT OUTER OUTPUT OVER OVERLAPS PAD PARAMETER PARTIAL PARTITION PASCAL PATH PCTFREE PERCENT
PIVOT PLAN POSITION PRECISION PREPARE PRESERVE PRIMARY PRINT PRIOR PRIVILEGES PROC
PROCEDURE PUBLIC RAISERROR RANGE RAW READ READS READTEXT REAL RECONFIGURE RECURSIVE REF
REFERENCES REFERENCING RELATIVE RENAME REPLICATION RESIGNAL RESOURCE RESTORE RESTRICT
RESULT RETURN RETURNS REVERT REVOKE RIGHT ROLE ROLLBACK ROLLUP ROUTINE ROW ROWCOUNT
ROWGUIDCOL ROWID ROWNUM ROWS RULE SAVE SAVEPOINT SCHEMA SCOPE SCROLL SEARCH SECOND SECTION
SECURITYAUDIT SELECT SENSITIVE SEQUENCE SESSION SESSION_USER SET SETS SETUSER SHARE
SHUTDOWN SIGNAL SIMILAR SIZE SMALLINT SOME SPACE SPECIFIC SQL SQLCODE SQLERROR SQLEXCEPTION
SQLSTATE SQLWARNING START STATE STATIC STATISTICS SUBSTRING successor SUCCESSFUL SUM
SYNONYM SYSDATE SYSTEM SYSTEM_USER TABLE TABLESAMPLE TEMPORARY TERMINATE TEXT TEXTSIZE THAN
THEN TIME TIMESTAMP TIMEZONE_HOUR TIMEZONE_MINUTE TO TOP TRAILING TRAN TRANSACTION TRANSLATE
TRANSLATION TREAT TRIGGER TRIM TRUE TRUNCATE TSEQUAL UID UNDER UNDO UNION UNIQUE UNKNOWN
UNNEST UNPIVOT UNTIL UPDATE UPDATETEXT UPPER USAGE USE USER USING VALIDATE VALUE VALUES
VARCHAR VARCHAR2 VARIABLE VARYING VIEW WAITFOR WHEN WHENEVER WHERE WHILE WITH WITHOUT WORK
WRITE WRITETEXT XMLELEMENT YEAR ZONE
""".split())
