# -*- coding: utf-8 -*-
"""
Relaciona sema TV stanice, izvedena iskljucivo iz PMOV dijagrama
PMOV_TV_stanica_2_1_1.vsdx (55 entiteta, 45 veza, 7 specijalizacija).

Svaka tabela nosi 'src' -- tacan PMOV element iz kojeg je nastala.
Imena su ASCII, VELIKA_SLOVA_SA_PODVLAKOM (konvencija iz primera TV_stanica_v7).
"""

ID   = 'CHAR(18)'
RB   = 'INTEGER'
N    = 'VARCHAR(60)'
T60  = 'VARCHAR(60)'
T30  = 'VARCHAR(30)'
T20  = 'VARCHAR(20)'
TXT  = 'VARCHAR(255)'
NOV  = 'DECIMAL(12,2)'
PROC = 'DECIMAL(5,2)'
D    = 'DATE'
VR   = 'TIME'
INT  = 'INTEGER'

TABLES = []

def T(name, src, cols, pk, fks=(), note=''):
    TABLES.append(dict(name=name, src=src, cols=cols, pk=list(pk),
                       fks=[dict(zip(('name','child','parent','pcols'), f)) for f in fks],
                       note=note))

def C(n, t, null=True, d=''):
    return dict(n=n, t=t, null=null, d=d)

# =====================================================================
# 1. ORGANIZACIJA I KADROVI
# =====================================================================
T('ORGANIZACIONA_JEDINICA',
  'jak entitet ORGANIZACIONA JEDINICA + rekurzivna veza PODREDJENA (0,N)-(0,1)',
  [C('SIFRA_JEDINICE', ID, False, 'PK - SIFRA JEDINICE'),
   C('SIFRA_NADREDJENE_JEDINICE', ID, True, 'FK - veza PODREDJENA (nadredjena jedinica)'),
   C('NAZIV_JEDINICE', N, False, 'NAZIV JEDINICE'),
   C('TIP_JEDINICE', T30, True, 'TIP JEDINICE'),
   C('OPIS_DELATNOSTI', TXT, True, 'OPIS DELATNOSTI'),
   C('DATUM_OSNIVANJA', D, True, 'DATUM OSNIVANJA'),
   C('BROJ_ZAPOSLENIH', INT, True, 'BROJ ZAPOSLENIH - izvedeni atribut')],
  ['SIFRA_JEDINICE'],
  [('FK_ORGJED_PODREDJENA', ['SIFRA_NADREDJENE_JEDINICE'], 'ORGANIZACIONA_JEDINICA', ['SIFRA_JEDINICE'])])

T('ZAPOSLENI',
  'jak entitet ZAPOSLENI + veza RADI U: ZAPOSLENI (1,1) - ORGANIZACIONA JEDINICA (0,N)',
  [C('SIFRA_ZAPOSLENOG', ID, False, 'PK - SIFRA ZAPOSLENOG'),
   C('SIFRA_JEDINICE', ID, False, 'FK - veza RADI U'),
   C('JMBG', 'CHAR(13)', False, 'JMBG'),
   C('IME', T30, False, 'IME'),
   C('PREZIME', T30, False, 'PREZIME'),
   C('RADNO_MESTO', T60, True, 'RADNO MESTO'),
   C('DATUM_ZAPOSLENJA', D, True, 'DATUM ZAPOSLENJA'),
   C('OSNOVNA_ZARADA', NOV, True, 'OSNOVNA ZARADA'),
   C('STATUS_ZAPOSLENJA', T20, True, 'STATUS ZAPOSLENJA')],
  ['SIFRA_ZAPOSLENOG'],
  [('FK_ZAPOSLENI_RADI_U', ['SIFRA_JEDINICE'], 'ORGANIZACIONA_JEDINICA', ['SIFRA_JEDINICE'])])

T('UREDNIK', 'podtip ZAPOSLENI -> UREDNIK (specijalizacija)',
  [C('SIFRA_ZAPOSLENOG', ID, False, 'PK = FK ka ZAPOSLENI'),
   C('NIVO_OVLASCENJA', T30, True, 'NIVO OVLASCENJA'),
   C('REDAKCIJA', T60, True, 'REDAKCIJA')],
  ['SIFRA_ZAPOSLENOG'],
  [('FK_UREDNIK_ZAPOSLENI', ['SIFRA_ZAPOSLENOG'], 'ZAPOSLENI', ['SIFRA_ZAPOSLENOG'])])

T('NOVINAR_REPORTER', 'podtip ZAPOSLENI -> NOVINAR / REPORTER',
  [C('SIFRA_ZAPOSLENOG', ID, False, 'PK = FK ka ZAPOSLENI'),
   C('OBLAST_IZVESTAVANJA', T60, True, 'OBLAST IZVESTAVANJA'),
   C('BROJ_NOVINARSKE_LEGITIM', T20, True, 'BROJ NOVINARSKE LEGITIMACIJE')],
  ['SIFRA_ZAPOSLENOG'],
  [('FK_NOVINAR_ZAPOSLENI', ['SIFRA_ZAPOSLENOG'], 'ZAPOSLENI', ['SIFRA_ZAPOSLENOG'])])

T('TEHNICKO_OSOBLJE', 'podtip ZAPOSLENI -> TEHNICKO OSOBLJE',
  [C('SIFRA_ZAPOSLENOG', ID, False, 'PK = FK ka ZAPOSLENI'),
   C('SPECIJALIZACIJA', T60, True, 'SPECIJALIZACIJA'),
   C('TIP_EKIPE', T30, True, 'TIP EKIPE')],
  ['SIFRA_ZAPOSLENOG'],
  [('FK_TEHOSOB_ZAPOSLENI', ['SIFRA_ZAPOSLENOG'], 'ZAPOSLENI', ['SIFRA_ZAPOSLENOG'])])

T('REFERENT', 'podtip ZAPOSLENI -> REFERENT',
  [C('SIFRA_ZAPOSLENOG', ID, False, 'PK = FK ka ZAPOSLENI'),
   C('TIP_REFERENTA', T30, True, 'TIP REFERENTA'),
   C('NIVO_OVLASCENJA', T30, True, 'NIVO OVLASCENJA')],
  ['SIFRA_ZAPOSLENOG'],
  [('FK_REFERENT_ZAPOSLENI', ['SIFRA_ZAPOSLENOG'], 'ZAPOSLENI', ['SIFRA_ZAPOSLENOG'])])

T('SERVISERI', 'podtip ZAPOSLENI -> SERVISERI',
  [C('SIFRA_ZAPOSLENOG', ID, False, 'PK = FK ka ZAPOSLENI'),
   C('LICENCA', T60, True, 'LICENCA')],
  ['SIFRA_ZAPOSLENOG'],
  [('FK_SERVISERI_ZAPOSLENI', ['SIFRA_ZAPOSLENOG'], 'ZAPOSLENI', ['SIFRA_ZAPOSLENOG'])])

# =====================================================================
# 2. OPREMA
# =====================================================================
T('OPREMA', 'jak entitet OPREMA',
  [C('INVENTARSKI_BROJ', ID, False, 'PK - INVENTARSKI BROJ'),
   C('NAZIV_OPREME', N, False, 'NAZIV OPREME'),
   C('MODEL', T60, True, 'MODEL'),
   C('PROIZVODJAC', T60, True, 'PROIZVODJAC'),
   C('STATUS_OPREME', T20, True, 'STATUS OPREME'),
   C('DATUM_NABAVKE', D, True, 'DATUM NABAVKE'),
   C('GARANCIJA_DO', D, True, 'GARANCIJA DO'),
   C('NABAVNA_VREDNOST', NOV, True, 'NABAVNA VREDNOST')],
  ['INVENTARSKI_BROJ'])

T('SNIMATELJSKA_OPREMA', 'podtip OPREMA -> SNIMATELJSKA OPREMA',
  [C('INVENTARSKI_BROJ', ID, False, 'PK = FK ka OPREMA'),
   C('TIP_MEMORIJSKOG_SKLADISTA', T30, True, 'TIP MEMORIJSKOG SKLADISTA'),
   C('REZOLUCIJA', T20, True, 'REZOLUCIJA'),
   C('TIP_KAMERE', T30, True, 'TIP KAMERE')],
  ['INVENTARSKI_BROJ'],
  [('FK_SNIMOPR_OPREMA', ['INVENTARSKI_BROJ'], 'OPREMA', ['INVENTARSKI_BROJ'])])

T('STUDIJSKA_I_EMISIONA_OPREMA', 'podtip OPREMA -> STUDIJSKA I EMISIONA OPREMA',
  [C('INVENTARSKI_BROJ', ID, False, 'PK = FK ka OPREMA'),
   C('LOKACIJA_U_STUDIJU', T60, True, 'LOKACIJA U STUDIJU')],
  ['INVENTARSKI_BROJ'],
  [('FK_STUDOPR_OPREMA', ['INVENTARSKI_BROJ'], 'OPREMA', ['INVENTARSKI_BROJ'])])

T('AUDIO_OPREMA', 'podtip STUDIJSKA I EMISIONA OPREMA -> AUDIO OPREMA',
  [C('INVENTARSKI_BROJ', ID, False, 'PK = FK ka STUDIJSKA_I_EMISIONA_OPREMA'),
   C('TIP', T30, True, 'TIP'),
   C('FREKVENCIJA', T20, True, 'FREKVENCIJA')],
  ['INVENTARSKI_BROJ'],
  [('FK_AUDIOOPR_STUDOPR', ['INVENTARSKI_BROJ'], 'STUDIJSKA_I_EMISIONA_OPREMA', ['INVENTARSKI_BROJ'])])

T('SVETLOSNA_OPREMA', 'podtip STUDIJSKA I EMISIONA OPREMA -> SVETLOSNA OPREMA',
  [C('INVENTARSKI_BROJ', ID, False, 'PK = FK ka STUDIJSKA_I_EMISIONA_OPREMA'),
   C('SNAGA', T20, True, 'SNAGA'),
   C('TIP_SVETLOSTI', T30, True, 'TIP SVETLOSTI')],
  ['INVENTARSKI_BROJ'],
  [('FK_SVETLOPR_STUDOPR', ['INVENTARSKI_BROJ'], 'STUDIJSKA_I_EMISIONA_OPREMA', ['INVENTARSKI_BROJ'])])

T('ZADUZENJE_OPREME',
  'veza ZADUZENA: ZAPOSLENI (0,N) - OPREMA (0,N), sa atributima veze',
  [C('SIFRA_ZAPOSLENOG', ID, False, 'PK/FK ka ZAPOSLENI'),
   C('INVENTARSKI_BROJ', ID, False, 'PK/FK ka OPREMA'),
   C('DATUM_ZADUZENJA', D, False, 'PK - atribut veze DATUM ZADUZENJA'),
   C('DATUM_RAZDUZENJA', D, True, 'atribut veze DATUM RAZDUZENJA'),
   C('STANJE_PRI_VRACANJU', TXT, True, 'atribut veze STANJE PRI VRACANJU')],
  ['SIFRA_ZAPOSLENOG', 'INVENTARSKI_BROJ', 'DATUM_ZADUZENJA'],
  [('FK_ZADUZ_ZAPOSLENI', ['SIFRA_ZAPOSLENOG'], 'ZAPOSLENI', ['SIFRA_ZAPOSLENOG']),
   ('FK_ZADUZ_OPREMA', ['INVENTARSKI_BROJ'], 'OPREMA', ['INVENTARSKI_BROJ'])])

T('SERVISIRANJE_OPREME',
  'veza SERVISIRANJE: SERVISERI (0,N) - OPREMA (0,N), sa atributima veze',
  [C('SIFRA_ZAPOSLENOG', ID, False, 'PK/FK ka SERVISERI'),
   C('INVENTARSKI_BROJ', ID, False, 'PK/FK ka OPREMA'),
   C('DATUM_SERVISA', D, False, 'PK - atribut veze DATUM SERVISA'),
   C('OPIS_RADOVA', TXT, True, 'atribut veze OPIS RADOVA'),
   C('TROSAK', NOV, True, 'atribut veze TROSAK')],
  ['SIFRA_ZAPOSLENOG', 'INVENTARSKI_BROJ', 'DATUM_SERVISA'],
  [('FK_SERVIS_SERVISERI', ['SIFRA_ZAPOSLENOG'], 'SERVISERI', ['SIFRA_ZAPOSLENOG']),
   ('FK_SERVIS_OPREMA', ['INVENTARSKI_BROJ'], 'OPREMA', ['INVENTARSKI_BROJ'])])

# =====================================================================
# 3. PRODUKCIJA
# =====================================================================
T('PROJEKAT_PRODUKCIJE',
  'jak entitet PROJEKAT PRODUKCIJE + UREDJUJE: UREDNIK (0,N)-(1,1) + PROIZVODI: PROJEKAT (0,1)-EMISIJA (0,N)',
  [C('SIFRA_PROJEKTA', ID, False, 'PK - SIFRA PROJEKTA'),
   C('SIFRA_UREDNIKA', ID, False, 'FK - veza UREDJUJE'),
   C('SIFRA_EMISIJE', ID, True, 'FK - veza PROIZVODI'),
   C('NAZIV_PROJEKTA', N, False, 'NAZIV PROJEKTA'),
   C('DATUM_POCETKA', D, True, 'DATUM POCETKA'),
   C('DATUM_ZAVRSETKA', D, True, 'DATUM ZAVRSETKA'),
   C('ODOBREN_BUDZET', NOV, True, 'ODOBREN BUDZET'),
   C('STATUS_PROJEKTA', T20, True, 'STATUS PROJEKTA'),
   C('VRSTA_PRODUKCIJE', T30, True, 'VRSTA PRODUKCIJE'),
   C('OPIS_PROJEKTA', TXT, True, 'OPIS PROJEKTA')],
  ['SIFRA_PROJEKTA'],
  [('FK_PROJEKAT_UREDJUJE', ['SIFRA_UREDNIKA'], 'UREDNIK', ['SIFRA_ZAPOSLENOG']),
   ('FK_PROJEKAT_PROIZVODI', ['SIFRA_EMISIJE'], 'EMISIJA', ['SIFRA_EMISIJE'])])

T('AKTIVNOST_PRODUKCIJE',
  'slab entitet AKTIVNOST PRODUKCIJE; identifikujuca veza SASTOJI SE OD: PROJEKAT (1,N) - AKTIVNOST (1,1)',
  [C('SIFRA_PROJEKTA', ID, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_AKTIVNOSTI', RB, False, 'PK - parcijalni kljuc RB AKTIVNOSTI'),
   C('NAZIV_AKTIVNOSTI', N, False, 'NAZIV AKTIVNOSTI'),
   C('DATUM_OD', D, True, 'DATUM OD'),
   C('DATUM_DO', D, True, 'DATUM DO'),
   C('VRSTA_AKTIVNOSTI', T30, True, 'VRSTA AKTIVNOSTI'),
   C('LOKACIJA_SNIMANJA', T60, True, 'LOKACIJA SNIMANJA'),
   C('STATUS_AKTIVNOSTI', T20, True, 'STATUS AKTIVNOSTI')],
  ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI'],
  [('FK_AKTIVNOST_PROJEKAT', ['SIFRA_PROJEKTA'], 'PROJEKAT_PRODUKCIJE', ['SIFRA_PROJEKTA'])])

T('TROSAK_PRODUKCIJE',
  'slab entitet TROSAK PRODUKCIJE; identifikujuca veza IZAZIVA: AKTIVNOST (0,N) - TROSAK (1,1); DOKUMENTOVAN: TROSAK (0,1) - FAKTURA (0,N)',
  [C('SIFRA_PROJEKTA', ID, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_AKTIVNOSTI', RB, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_TROSKA', RB, False, 'PK - parcijalni kljuc RB TROSKA'),
   C('BROJ_FAKTURE', ID, True, 'FK - veza DOKUMENTOVAN'),
   C('VRSTA_TROSKA', T30, True, 'VRSTA TROSKA'),
   C('IZNOS', NOV, False, 'IZNOS'),
   C('DATUM_NASTANKA', D, True, 'DATUM NASTANKA'),
   C('OPIS_TROSKA', TXT, True, 'OPIS TROSKA')],
  ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI', 'RB_TROSKA'],
  [('FK_TROSAK_IZAZIVA', ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI'], 'AKTIVNOST_PRODUKCIJE', ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI']),
   ('FK_TROSAK_DOKUMENTOVAN', ['BROJ_FAKTURE'], 'FAKTURA', ['BROJ_FAKTURE'])])

T('ANGAZOVANJE_NA_AKTIVNOSTI',
  'veza ANGAZUJE: ZAPOSLENI (0,N) - AKTIVNOST PRODUKCIJE (0,N), sa atributima veze',
  [C('SIFRA_PROJEKTA', ID, False, 'PK/FK ka AKTIVNOST_PRODUKCIJE'),
   C('RB_AKTIVNOSTI', RB, False, 'PK/FK ka AKTIVNOST_PRODUKCIJE'),
   C('SIFRA_ZAPOSLENOG', ID, False, 'PK/FK ka ZAPOSLENI'),
   C('ULOGA_NA_SNIMANJU', T60, True, 'atribut veze ULOGA NA SNIMANJU'),
   C('DATUM_OD', D, True, 'atribut veze DATUM OD'),
   C('DATUM_DO', D, True, 'atribut veze DATUM DO'),
   C('BROJ_ANGAZOVANIH_SATI', INT, True, 'atribut veze BROJ ANGAZOVANIH SATI')],
  ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI', 'SIFRA_ZAPOSLENOG'],
  [('FK_ANGAZ_AKTIVNOST', ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI'], 'AKTIVNOST_PRODUKCIJE', ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI']),
   ('FK_ANGAZ_ZAPOSLENI', ['SIFRA_ZAPOSLENOG'], 'ZAPOSLENI', ['SIFRA_ZAPOSLENOG'])])

T('REZERVACIJA_OPREME',
  'veza ZADUZUJE: OPREMA (0,N) - AKTIVNOST PRODUKCIJE (0,N), sa atributima veze',
  [C('SIFRA_PROJEKTA', ID, False, 'PK/FK ka AKTIVNOST_PRODUKCIJE'),
   C('RB_AKTIVNOSTI', RB, False, 'PK/FK ka AKTIVNOST_PRODUKCIJE'),
   C('INVENTARSKI_BROJ', ID, False, 'PK/FK ka OPREMA'),
   C('DATUM_REZERVACIJE', D, True, 'atribut veze DATUM REZERVACIJE'),
   C('TRAJANJE_ZADUZENJA', INT, True, 'atribut veze TRAJANJE ZADUZENJA (dana)')],
  ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI', 'INVENTARSKI_BROJ'],
  [('FK_REZERV_AKTIVNOST', ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI'], 'AKTIVNOST_PRODUKCIJE', ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI']),
   ('FK_REZERV_OPREMA', ['INVENTARSKI_BROJ'], 'OPREMA', ['INVENTARSKI_BROJ'])])

T('SIROVI_SNIMAK',
  'jak entitet SIROVI SNIMAK + veza SNIMLJEN NA: SIROVI SNIMAK (1,1) - AKTIVNOST PRODUKCIJE (0,N)',
  [C('SIFRA_SNIMKA', ID, False, 'PK - SIFRA SNIMKA'),
   C('SIFRA_PROJEKTA', ID, False, 'FK - veza SNIMLJEN NA'),
   C('RB_AKTIVNOSTI', RB, False, 'FK - veza SNIMLJEN NA'),
   C('DATUM_SNIMANJA', D, True, 'DATUM SNIMANJA'),
   C('TRAJANJE', INT, True, 'TRAJANJE (sekundi)'),
   C('FORMAT_SNIMKA', T30, True, 'FORMAT SNIMKA'),
   C('LOKACIJA_SNIMKA', T60, True, 'LOKACIJA SNIMKA'),
   C('OCENA_KVALITETA', T20, True, 'OCENA KVALITETA')],
  ['SIFRA_SNIMKA'],
  [('FK_SNIMAK_SNIMLJEN_NA', ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI'], 'AKTIVNOST_PRODUKCIJE', ['SIFRA_PROJEKTA', 'RB_AKTIVNOSTI'])])

T('GRAFICKI_I_MUZICKI_ELEMENT', 'jak entitet GRAFICKI I MUZICKI ELEMENT',
  [C('SIFRA_ELEMENTA', ID, False, 'PK - SIFRA ELEMENTA'),
   C('NAZIV_ELEMENTA', N, False, 'NAZIV ELEMENTA'),
   C('TIP_ELEMENTA', T30, True, 'TIP ELEMENTA'),
   C('AUTOR', T60, True, 'AUTOR'),
   C('FORMAT', T30, True, 'FORMAT'),
   C('USLOV_KORISCENJA', TXT, True, 'USLOV KORISCENJA')],
  ['SIFRA_ELEMENTA'])

# =====================================================================
# 4. PROGRAM I EMITOVANJE
# =====================================================================
T('PROGRAMSKA_SEMA',
  'jak entitet PROGRAMSKA SEMA + veza ODOBRAVA: UREDNIK (0,N) - PROGRAMSKA SEMA (1,1)',
  [C('SIFRA_SEME', ID, False, 'PK - ID SEME'),
   C('SIFRA_UREDNIKA', ID, False, 'FK - veza ODOBRAVA'),
   C('NAZIV_SEME', N, False, 'NAZIV SEME'),
   C('SEZONA', T20, True, 'SEZONA'),
   C('VERZIJA_SEME', T20, True, 'VERZIJA SEME'),
   C('DATUM_OD', D, True, 'DATUM OD'),
   C('DATUM_DO', D, True, 'DATUM DO'),
   C('STATUS_SEME', T20, True, 'STATUS SEME'),
   C('DATUM_USVAJANJA', D, True, 'DATUM USVAJANJA')],
  ['SIFRA_SEME'],
  [('FK_PSEMA_ODOBRAVA', ['SIFRA_UREDNIKA'], 'UREDNIK', ['SIFRA_ZAPOSLENOG'])])

T('PROGRAMSKA_CELINA',
  'slab entitet PROGRAMSKA CELINA; identifikujuca veza SADRZI CELINE: PROGRAMSKA SEMA (1,N) - PROGRAMSKA CELINA (1,1)',
  [C('SIFRA_SEME', ID, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_CELINE', RB, False, 'PK - parcijalni kljuc RB CELINE'),
   C('NAZIV_CELINE', N, False, 'NAZIV CELINE'),
   C('TIP_CELINE', T30, True, 'TIP CELINE'),
   C('DATUM', D, True, 'DATUM'),
   C('VREME_OD', VR, True, 'VREME OD'),
   C('VREME_DO', VR, True, 'VREME DO')],
  ['SIFRA_SEME', 'RB_CELINE'],
  [('FK_PCELINA_PSEMA', ['SIFRA_SEME'], 'PROGRAMSKA_SEMA', ['SIFRA_SEME'])])

T('EMISIJA', 'jak entitet EMISIJA',
  [C('SIFRA_EMISIJE', ID, False, 'PK - SIFRA EMISIJE'),
   C('NAZIV_EMISIJE', N, False, 'NAZIV EMISIJE'),
   C('ZANR', T30, True, 'ZANR'),
   C('FORMAT_EMISIJE', T30, True, 'FORMAT EMISIJE'),
   C('PREDVIDJENO_TRAJANJE', INT, True, 'PREDVIDJENO TRAJANJE (minuta)'),
   C('CILJNA_PUBLIKA', T60, True, 'CILJNA PUBLIKA'),
   C('STATUS_EMISIJE', T20, True, 'STATUS EMISIJE'),
   C('PROGRAMSKI_ELABORAT', TXT, True, 'PROGRAMSKI ELABORAT')],
  ['SIFRA_EMISIJE'])

T('TERMIN_EMITOVANJA',
  'jak entitet TERMIN EMITOVANJA + OBUHVATA: PROGRAMSKA CELINA (1,N)-(1,1) + PLANIRANA: TERMIN (1,1) - EMISIJA (0,N)',
  [C('SIFRA_TERMINA', ID, False, 'PK - SIFRA TERMINA'),
   C('SIFRA_SEME', ID, False, 'FK - veza OBUHVATA'),
   C('RB_CELINE', RB, False, 'FK - veza OBUHVATA'),
   C('SIFRA_EMISIJE', ID, False, 'FK - veza PLANIRANA'),
   C('DATUM', D, False, 'DATUM'),
   C('VREME_POCETKA', VR, False, 'VREME POCETKA'),
   C('TRAJANJE_TERMINA', INT, True, 'TRAJANJE TERMINA (minuta)'),
   C('TIP_TERMINA', T30, True, 'TIP TERMINA'),
   C('ZONA_GLEDANOSTI', T20, True, 'ZONA GLEDANOSTI'),
   C('STATUS_TERMINA', T20, True, 'STATUS TERMINA'),
   C('REDNI_BROJ_REPRIZE', RB, True, 'REDNI BROJ REPRIZE')],
  ['SIFRA_TERMINA'],
  [('FK_TERMIN_OBUHVATA', ['SIFRA_SEME', 'RB_CELINE'], 'PROGRAMSKA_CELINA', ['SIFRA_SEME', 'RB_CELINE']),
   ('FK_TERMIN_PLANIRANA', ['SIFRA_EMISIJE'], 'EMISIJA', ['SIFRA_EMISIJE'])])

T('MEDIJSKI_SADRZAJ', 'jak entitet MEDIJSKI SADRZAJ (nadtip)',
  [C('SIFRA_SADRZAJA', ID, False, 'PK - SIFRA SADRZAJA'),
   C('NAZIV_SADRZAJA', N, False, 'NAZIV SADRZAJA'),
   C('TRAJANJE', INT, True, 'TRAJANJE (sekundi)'),
   C('FORMAT_ZAPISA', T30, True, 'FORMAT ZAPISA'),
   C('DATUM_ARHIVIRANJA', D, True, 'DATUM ARHIVIRANJA'),
   C('LOKACIJA_U_ARHIVI', T60, True, 'LOKACIJA U ARHIVI')],
  ['SIFRA_SADRZAJA'])

T('PRODUCIRANI_SADRZAJ', 'podtip MEDIJSKI SADRZAJ -> PRODUCIRANI SADRZAJ',
  [C('SIFRA_SADRZAJA', ID, False, 'PK = FK ka MEDIJSKI_SADRZAJ'),
   C('DATUM_PRODUKCIJE', D, True, 'DATUM PRODUKCIJE'),
   C('VERZIJA_MASTERA', T20, True, 'VERZIJA MASTERA')],
  ['SIFRA_SADRZAJA'],
  [('FK_MSPROD_MSADRZAJ', ['SIFRA_SADRZAJA'], 'MEDIJSKI_SADRZAJ', ['SIFRA_SADRZAJA'])])

T('NABAVLJENI_SADRZAJ',
  'podtip MEDIJSKI SADRZAJ -> NABAVLJENI SADRZAJ + veza NABAVLJEN PO: NABAVLJENI SADRZAJ (1,1) - UGOVOR O NABAVCI (1,N), sa atributima veze',
  [C('SIFRA_SADRZAJA', ID, False, 'PK = FK ka MEDIJSKI_SADRZAJ'),
   C('BROJ_UGOVORA', ID, False, 'FK - veza NABAVLJEN PO'),
   C('ZEMLJA_POREKLA', T60, True, 'ZEMLJA POREKLA'),
   C('CENA_NABAVKE', NOV, True, 'CENA NABAVKE'),
   C('DATUM_PREUZIMANJA', D, True, 'atribut veze NABAVLJEN PO: DATUM PREUZIMANJA'),
   C('UGOVORENA_NAKNADA', NOV, True, 'atribut veze NABAVLJEN PO: UGOVORENA NAKNADA')],
  ['SIFRA_SADRZAJA'],
  [('FK_MSNAB_MSADRZAJ', ['SIFRA_SADRZAJA'], 'MEDIJSKI_SADRZAJ', ['SIFRA_SADRZAJA']),
   ('FK_MSNAB_NABAVLJEN_PO', ['BROJ_UGOVORA'], 'UGOVOR_O_NABAVCI', ['BROJ_UGOVORA'])])

T('REKLAMNI_SADRZAJ',
  'podtip MEDIJSKI SADRZAJ -> REKLAMNI SADRZAJ + veza DOSTAVLJA: OGLASIVAC (1,N) - REKLAMNI SADRZAJ (1,1)',
  [C('SIFRA_SADRZAJA', ID, False, 'PK = FK ka MEDIJSKI_SADRZAJ'),
   C('SIFRA_OGLASIVACA', ID, False, 'FK - veza DOSTAVLJA'),
   C('DATUM_PRIJEMA', D, True, 'DATUM PRIJEMA'),
   C('STATUS', T20, True, 'STATUS')],
  ['SIFRA_SADRZAJA'],
  [('FK_MSREK_MSADRZAJ', ['SIFRA_SADRZAJA'], 'MEDIJSKI_SADRZAJ', ['SIFRA_SADRZAJA']),
   ('FK_MSREK_DOSTAVLJA', ['SIFRA_OGLASIVACA'], 'OGLASIVAC', ['SIFRA_KLIJENTA'])])

T('ZAPIS_O_EMITOVANJU',
  'slab entitet ZAPIS O EMITOVANJU; identifikujuca veza REALIZOVAN: TERMIN (0,N) - ZAPIS (1,1); EVIDENTIRA: ZAPIS (1,1) - MEDIJSKI SADRZAJ (0,N)',
  [C('SIFRA_TERMINA', ID, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_EMITOVANJA', RB, False, 'PK - parcijalni kljuc RB EMITOVANJA'),
   C('SIFRA_SADRZAJA', ID, False, 'FK - veza EVIDENTIRA'),
   C('STATUS_REALIZACIJE', T20, True, 'STATUS REALIZACIJE'),
   C('STVARNO_VREME_POCETKA', VR, True, 'STVARNO VREME POC.'),
   C('STVARNO_TRAJANJE', INT, True, 'STVARNO TRAJANJE (sekundi)'),
   C('NAPOMENA_O_SMETNJAMA', TXT, True, 'NAPOMENA O SMETNJAMA'),
   C('OPERATER_EMITOVANJA', T60, True, 'OPERATER EMITOVANJA')],
  ['SIFRA_TERMINA', 'RB_EMITOVANJA'],
  [('FK_ZAPISEM_REALIZOVAN', ['SIFRA_TERMINA'], 'TERMIN_EMITOVANJA', ['SIFRA_TERMINA']),
   ('FK_ZAPISEM_EVIDENTIRA', ['SIFRA_SADRZAJA'], 'MEDIJSKI_SADRZAJ', ['SIFRA_SADRZAJA'])])

T('MONTAZA_SNIMKA',
  'veza MONTIRAN U: SIROVI SNIMAK (0,N) - MEDIJSKI SADRZAJ (0,N)',
  [C('SIFRA_SADRZAJA', ID, False, 'PK/FK ka MEDIJSKI_SADRZAJ'),
   C('SIFRA_SNIMKA', ID, False, 'PK/FK ka SIROVI_SNIMAK')],
  ['SIFRA_SADRZAJA', 'SIFRA_SNIMKA'],
  [('FK_MONTAZA_MSADRZAJ', ['SIFRA_SADRZAJA'], 'MEDIJSKI_SADRZAJ', ['SIFRA_SADRZAJA']),
   ('FK_MONTAZA_SNIMAK', ['SIFRA_SNIMKA'], 'SIROVI_SNIMAK', ['SIFRA_SNIMKA'])])

T('UGRADNJA_ELEMENTA',
  'veza UGRADJEN U: GRAFICKI I MUZICKI ELEMENT (0,N) - MEDIJSKI SADRZAJ (0,N), sa atributima veze',
  [C('SIFRA_SADRZAJA', ID, False, 'PK/FK ka MEDIJSKI_SADRZAJ'),
   C('SIFRA_ELEMENTA', ID, False, 'PK/FK ka GRAFICKI_I_MUZICKI_ELEMENT'),
   C('VREME_POJAVLJIVANJA', VR, True, 'atribut veze VREME POJAVLJIVANJA'),
   C('NACIN_KORISCENJA', T60, True, 'atribut veze NACIN KORISCENJA')],
  ['SIFRA_SADRZAJA', 'SIFRA_ELEMENTA'],
  [('FK_UGRADNJA_MSADRZAJ', ['SIFRA_SADRZAJA'], 'MEDIJSKI_SADRZAJ', ['SIFRA_SADRZAJA']),
   ('FK_UGRADNJA_ELEMENT', ['SIFRA_ELEMENTA'], 'GRAFICKI_I_MUZICKI_ELEMENT', ['SIFRA_ELEMENTA'])])

T('SADRZAJ_EMISIJE',
  'veza CINI: EMISIJA (1,N) - MEDIJSKI SADRZAJ (0,N), sa atributom veze',
  [C('SIFRA_EMISIJE', ID, False, 'PK/FK ka EMISIJA'),
   C('SIFRA_SADRZAJA', ID, False, 'PK/FK ka MEDIJSKI_SADRZAJ'),
   C('REDNI_BROJ_U_EMISIJI', RB, True, 'atribut veze REDNI BROJ U EMISIJI')],
  ['SIFRA_EMISIJE', 'SIFRA_SADRZAJA'],
  [('FK_SADREM_EMISIJA', ['SIFRA_EMISIJE'], 'EMISIJA', ['SIFRA_EMISIJE']),
   ('FK_SADREM_MSADRZAJ', ['SIFRA_SADRZAJA'], 'MEDIJSKI_SADRZAJ', ['SIFRA_SADRZAJA'])])

T('PRAVO_KORISCENJA', 'jak entitet PRAVO KORISCENJA',
  [C('BROJ_LICENCE', ID, False, 'PK - BROJ LICENCE'),
   C('VRSTA_PRAVA', T30, True, 'VRSTA PRAVA'),
   C('DATUM_OD', D, True, 'DATUM OD'),
   C('DATUM_DO', D, True, 'DATUM DO'),
   C('DOZVOLJENO_EMITOVANJA', INT, True, 'DOZVOLJENO EMITOVANJA'),
   C('ISKORISCENO_EMITOVANJA', INT, True, 'ISKORISCENO EMITOVANJA - izvedeni atribut'),
   C('TERITORIJA', T60, True, 'TERITORIJA'),
   C('NOSILAC_PRAVA', T60, True, 'NOSILAC PRAVA')],
  ['BROJ_LICENCE'])

T('POKRIVENOST_PRAVOM',
  'veza POKRIVA: PRAVO KORISCENJA (1,N) - MEDIJSKI SADRZAJ (0,N), sa atributom veze',
  [C('BROJ_LICENCE', ID, False, 'PK/FK ka PRAVO_KORISCENJA'),
   C('SIFRA_SADRZAJA', ID, False, 'PK/FK ka MEDIJSKI_SADRZAJ'),
   C('OBLAST_POKRIVENOSTI', T60, True, 'atribut veze OBLAST POKRIVENOSTI')],
  ['BROJ_LICENCE', 'SIFRA_SADRZAJA'],
  [('FK_POKRIV_PRAVO', ['BROJ_LICENCE'], 'PRAVO_KORISCENJA', ['BROJ_LICENCE']),
   ('FK_POKRIV_MSADRZAJ', ['SIFRA_SADRZAJA'], 'MEDIJSKI_SADRZAJ', ['SIFRA_SADRZAJA'])])

T('POVRATNA_INFO_GLEDALACA',
  'jak entitet POVRATNA INFO. GLEDALACA + veza ODNOSI SE NA: POVRATNA INFO (0,1) - EMISIJA (0,N)',
  [C('BROJ_PRIJAVE', ID, False, 'PK - BROJ PRIJAVE'),
   C('SIFRA_EMISIJE', ID, True, 'FK - veza ODNOSI SE NA'),
   C('DATUM_PRIJEMA', D, True, 'DATUM PRIJEMA'),
   C('VRSTA_PRIJAVE', T30, True, 'VRSTA PRIJAVE'),
   C('KANAL_PRIJEMA', T30, True, 'KANAL PRIJEMA'),
   C('SADRZAJ_PRIJAVE', TXT, True, 'SADRZAJ PRIJAVE'),
   C('STATUS_OBRADE', T20, True, 'STATUS OBRADE'),
   C('DATUM_ODGOVORA', D, True, 'DATUM ODGOVORA'),
   C('PROFIL_GLEDAOCA', T60, True, 'PROFIL GLEDAOCA')],
  ['BROJ_PRIJAVE'],
  [('FK_POVRINF_EMISIJA', ['SIFRA_EMISIJE'], 'EMISIJA', ['SIFRA_EMISIJE'])])

T('MERENJE_GLEDANOSTI', 'jak entitet MERENJE GLEDANOSTI',
  [C('SIFRA_MERENJA', ID, False, 'PK - SIFRA MERENJA'),
   C('DATUM_MERENJA', D, True, 'DATUM MERENJA'),
   C('IZVOR_MERENJA', T60, True, 'IZVOR MERENJA'),
   C('CILJNA_GRUPA', T60, True, 'CILJNA GRUPA'),
   C('RATING', PROC, True, 'RATING'),
   C('SHARE', PROC, True, 'SHARE'),
   C('BROJ_GLEDALACA', INT, True, 'BROJ GLEDALACA'),
   C('PROSECNO_GLEDANJE', INT, True, 'PROSECNO GLEDANJE (minuta)')],
  ['SIFRA_MERENJA'])

T('MERENJE_EMISIJE',
  'veza MERENA: MERENJE GLEDANOSTI (1,N) - EMISIJA (0,N), sa atributima veze',
  [C('SIFRA_MERENJA', ID, False, 'PK/FK ka MERENJE_GLEDANOSTI'),
   C('SIFRA_EMISIJE', ID, False, 'PK/FK ka EMISIJA'),
   C('OSTVARENI_RATING', PROC, True, 'atribut veze OSTVARENI RATING'),
   C('UDEO_U_TERMINU', PROC, True, 'atribut veze UDEO U TERMINU')],
  ['SIFRA_MERENJA', 'SIFRA_EMISIJE'],
  [('FK_MERENJEEM_MERENJE', ['SIFRA_MERENJA'], 'MERENJE_GLEDANOSTI', ['SIFRA_MERENJA']),
   ('FK_MERENJEEM_EMISIJA', ['SIFRA_EMISIJE'], 'EMISIJA', ['SIFRA_EMISIJE'])])

# =====================================================================
# 5. MARKETING I PRODAJA
# =====================================================================
T('CENOVNIK_REKL_TERMINA', 'jak entitet CENOVNIK REKL. TERMINA',
  [C('SIFRA_CENOVNIKA', ID, False, 'PK - SIFRA CENOVNIKA'),
   C('VAZI_OD', D, True, 'VAZI OD'),
   C('VAZI_DO', D, True, 'VAZI DO'),
   C('ZONA', T30, True, 'ZONA'),
   C('CENA_PO_SEKUNDI', NOV, True, 'CENA PO SEKUNDI'),
   C('TIP_CENOVNOG_PAKETA', T30, True, 'TIP CENOVNOG PAKETA'),
   C('OPIS_CENOVNOG_PAKETA', TXT, True, 'OPIS CENOVNOG PAKETA')],
  ['SIFRA_CENOVNIKA'])

T('REKLAMNI_BLOK',
  'jak entitet REKLAMNI BLOK + ZAKUPLJEN U: BLOK (1,1) - TERMIN (0,N) + TARIFIRAN: CENOVNIK (1,N) - BLOK (1,1)',
  [C('SIFRA_BLOKA', ID, False, 'PK - SIFRA BLOKA'),
   C('SIFRA_TERMINA', ID, False, 'FK - veza ZAKUPLJEN U'),
   C('SIFRA_CENOVNIKA', ID, False, 'FK - veza TARIFIRAN'),
   C('DATUM', D, True, 'DATUM'),
   C('VREME_POCETKA', VR, True, 'VREME POCETKA'),
   C('TRAJANJE_BLOKA', INT, True, 'TRAJANJE BLOKA (sekundi)'),
   C('ZAKUPLJENO_SEKUNDI', INT, True, 'ZAKUPLJENO SEKUNDI - izvedeni atribut'),
   C('SLOBODNO_SEKUNDI', INT, True, 'SLOBODNO SEKUNDI - izvedeni atribut'),
   C('ISKORISCENOST', PROC, True, 'ISKORISCENOST - izvedeni atribut'),
   C('STATUS_BLOKA', T20, True, 'STATUS BLOKA')],
  ['SIFRA_BLOKA'],
  [('FK_RBLOK_ZAKUPLJEN_U', ['SIFRA_TERMINA'], 'TERMIN_EMITOVANJA', ['SIFRA_TERMINA']),
   ('FK_RBLOK_TARIFIRAN', ['SIFRA_CENOVNIKA'], 'CENOVNIK_REKL_TERMINA', ['SIFRA_CENOVNIKA'])])

T('EMITOVANJE_REKLAME',
  'slab entitet EMITOVANJE REKLAME; identifikujuca veza SADRZI SPOT: REKLAMNI BLOK (1,N) - (1,1); PRIKAZUJE: (1,1) - REKLAMNI SADRZAJ (0,N); UGOVOREN: (1,1) - STAVKA UGOVORA (0,N)',
  [C('SIFRA_BLOKA', ID, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_U_BLOKU', RB, False, 'PK - parcijalni kljuc RB U BLOKU'),
   C('SIFRA_SADRZAJA', ID, False, 'FK - veza PRIKAZUJE'),
   C('BROJ_UGOVORA', ID, False, 'FK - veza UGOVOREN'),
   C('RB_STAVKE_UGOVORA', RB, False, 'FK - veza UGOVOREN'),
   C('DATUM_EMITOVANJA', D, True, 'DATUM EMITOVANJA'),
   C('VREME_EMITOVANJA', VR, True, 'VREME EMITOVANJA'),
   C('TRAJANJE_SPOTA', INT, True, 'TRAJANJE SPOTA (sekundi)'),
   C('NAPLACENI_IZNOS', NOV, True, 'NAPLACENI IZNOS'),
   C('STATUS_NAPLATE', T20, True, 'STATUS NAPLATE')],
  ['SIFRA_BLOKA', 'RB_U_BLOKU'],
  [('FK_EMREK_SADRZI_SPOT', ['SIFRA_BLOKA'], 'REKLAMNI_BLOK', ['SIFRA_BLOKA']),
   ('FK_EMREK_PRIKAZUJE', ['SIFRA_SADRZAJA'], 'REKLAMNI_SADRZAJ', ['SIFRA_SADRZAJA']),
   ('FK_EMREK_UGOVOREN', ['BROJ_UGOVORA', 'RB_STAVKE_UGOVORA'], 'STAVKA_UGOVORA', ['BROJ_UGOVORA', 'RB_STAVKE'])])

T('KLIJENT', 'jak entitet KLIJENT (nadtip); ADRESA je slozeni atribut',
  [C('SIFRA_KLIJENTA', ID, False, 'PK - SIFRA KLIJENTA'),
   C('NAZIV_KLIJENTA', N, False, 'NAZIV KLIJENTA'),
   C('PIB', 'CHAR(9)', True, 'PIB'),
   C('MATICNI_BROJ', 'CHAR(8)', True, 'MATICNI BROJ'),
   C('ULICA_I_BROJ', T60, True, 'ADRESA / ULICA I BROJ (slozeni atribut)'),
   C('GRAD', T30, True, 'ADRESA / GRAD (slozeni atribut)'),
   C('POSTANSKI_BROJ', 'CHAR(5)', True, 'ADRESA / POSTANSKI BROJ (slozeni atribut)'),
   C('KONTAKT_OSOBA', T60, True, 'KONTAKT OSOBA')],
  ['SIFRA_KLIJENTA'])

T('OGLASIVAC', 'podtip KLIJENT -> OGLASIVAC',
  [C('SIFRA_KLIJENTA', ID, False, 'PK = FK ka KLIJENT'),
   C('BRANSA', T60, True, 'BRANSA'),
   C('GODISNJI_BUDZET', NOV, True, 'GODISNJI BUDZET')],
  ['SIFRA_KLIJENTA'],
  [('FK_OGLASIVAC_KLIJENT', ['SIFRA_KLIJENTA'], 'KLIJENT', ['SIFRA_KLIJENTA'])])

T('KUPAC_SADRZAJA', 'podtip KLIJENT -> KUPAC SADRZAJA',
  [C('SIFRA_KLIJENTA', ID, False, 'PK = FK ka KLIJENT'),
   C('TIP_MEDIJA', T30, True, 'TIP MEDIJA'),
   C('TERITORIJA_EMITOVANJA', T60, True, 'TERITORIJA EMITOVANJA')],
  ['SIFRA_KLIJENTA'],
  [('FK_KUPACSAD_KLIJENT', ['SIFRA_KLIJENTA'], 'KLIJENT', ['SIFRA_KLIJENTA'])])

T('UGOVOR',
  'jak entitet UGOVOR (nadtip) + veza SKLAPA: KLIJENT (0,N) - UGOVOR (0,1)',
  [C('BROJ_UGOVORA', ID, False, 'PK - BROJ UGOVORA'),
   C('SIFRA_KLIJENTA', ID, True, 'FK - veza SKLAPA'),
   C('DATUM_SKLAPANJA', D, True, 'DATUM SKLAPANJA'),
   C('VAZI_OD', D, True, 'VAZI OD'),
   C('VAZI_DO', D, True, 'VAZI DO'),
   C('UKUPNA_VREDNOST', NOV, True, 'UKUPNA VREDNOST - izvedeni atribut'),
   C('STATUS_UGOVORA', T20, True, 'STATUS UGOVORA')],
  ['BROJ_UGOVORA'],
  [('FK_UGOVOR_SKLAPA', ['SIFRA_KLIJENTA'], 'KLIJENT', ['SIFRA_KLIJENTA'])])

T('STAVKA_UGOVORA',
  'slab entitet STAVKA UGOVORA; identifikujuca veza PRECIZIRA: UGOVOR (1,N) - STAVKA (1,1)',
  [C('BROJ_UGOVORA', ID, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_STAVKE', RB, False, 'PK - parcijalni kljuc RB STAVKE'),
   C('OPIS_STAVKE', TXT, True, 'OPIS STAVKE'),
   C('KOLICINA_SEKUNDE', INT, True, 'KOLICINA / SEKUNDE'),
   C('JEDINICNA_CENA', NOV, True, 'JEDINICNA CENA'),
   C('POPUST', PROC, True, 'POPUST'),
   C('VREDNOST_STAVKE', NOV, True, 'VREDNOST STAVKE - izvedeni atribut')],
  ['BROJ_UGOVORA', 'RB_STAVKE'],
  [('FK_STUGOV_PRECIZIRA', ['BROJ_UGOVORA'], 'UGOVOR', ['BROJ_UGOVORA'])])

T('UGOVOR_O_OGLASAVANJU', 'podtip UGOVOR -> UGOVOR O OGLASAVANJU',
  [C('BROJ_UGOVORA', ID, False, 'PK = FK ka UGOVOR'),
   C('UGOVORENI_TERMINI', TXT, True, 'UGOVORENI TERMINI')],
  ['BROJ_UGOVORA'],
  [('FK_UGOGL_UGOVOR', ['BROJ_UGOVORA'], 'UGOVOR', ['BROJ_UGOVORA'])])

T('UGOVOR_O_PRODAJI_TV_SADRZAJA', 'podtip UGOVOR -> UGOVOR O PRODAJI TV SADRZAJA',
  [C('BROJ_UGOVORA', ID, False, 'PK = FK ka UGOVOR'),
   C('PRENOS_VLASNISTVA', T20, True, 'PRENOS VLASNISTVA'),
   C('OBIM_USTUPLJENIH_PRAVA', TXT, True, 'OBIM USTUPLJENIH PRAVA')],
  ['BROJ_UGOVORA'],
  [('FK_UGPROD_UGOVOR', ['BROJ_UGOVORA'], 'UGOVOR', ['BROJ_UGOVORA'])])

T('UGOVOR_O_NABAVCI',
  'podtip UGOVOR -> UGOVOR O NABAVCI + veza UGOVARA: DOBAVLJAC (0,N) - UGOVOR O NABAVCI (1,1)',
  [C('BROJ_UGOVORA', ID, False, 'PK = FK ka UGOVOR'),
   C('SIFRA_DOBAVLJACA', ID, False, 'FK - veza UGOVARA'),
   C('VRSTA_REKLAMIRANJA', T30, True, 'VRSTA REKLAMIRANJA'),
   C('ROK_ISPORUKE', D, True, 'ROK ISPORUKE'),
   C('USLOVI_PLACANJA', TXT, True, 'USLOVI PLACANJA')],
  ['BROJ_UGOVORA'],
  [('FK_UGNAB_UGOVOR', ['BROJ_UGOVORA'], 'UGOVOR', ['BROJ_UGOVORA']),
   ('FK_UGNAB_UGOVARA', ['SIFRA_DOBAVLJACA'], 'DOBAVLJAC', ['SIFRA_DOBAVLJACA'])])

T('USTUPANJE_SADRZAJA',
  'veza USTUPA: UGOVOR O PRODAJI TV SADRZAJA (1,N) - PRODUCIRANI SADRZAJ (0,N), sa atributima veze',
  [C('BROJ_UGOVORA', ID, False, 'PK/FK ka UGOVOR_O_PRODAJI_TV_SADRZAJA'),
   C('SIFRA_SADRZAJA', ID, False, 'PK/FK ka PRODUCIRANI_SADRZAJ'),
   C('UGOVORENA_CENA', NOV, True, 'atribut veze UGOVORENA CENA'),
   C('OBIM_USTUPANJA', TXT, True, 'atribut veze OBIM USTUPANJA')],
  ['BROJ_UGOVORA', 'SIFRA_SADRZAJA'],
  [('FK_USTUP_UGPROD', ['BROJ_UGOVORA'], 'UGOVOR_O_PRODAJI_TV_SADRZAJA', ['BROJ_UGOVORA']),
   ('FK_USTUP_MSPROD', ['SIFRA_SADRZAJA'], 'PRODUCIRANI_SADRZAJ', ['SIFRA_SADRZAJA'])])

# =====================================================================
# 6. NABAVKA
# =====================================================================
T('PLAN_NABAVKE', 'jak entitet PLAN NABAVKE',
  [C('SIFRA_PLANA', ID, False, 'PK - SIFRA PLANA'),
   C('GODINA_PLANA', INT, True, 'GODINA PLANA'),
   C('DATUM_DONOSENJA', D, True, 'DATUM DONOSENJA'),
   C('STATUS_PLANA', T20, True, 'STATUS PLANA'),
   C('UKUPNA_VREDNOST', NOV, True, 'UKUPNA VREDNOST - izvedeni atribut'),
   C('DONOSILAC_PLANA', T60, True, 'DONOSILAC PLANA')],
  ['SIFRA_PLANA'])

T('ZAHTEV_ZA_NABAVKU',
  'jak entitet ZAHTEV ZA NABAVKU + PODNOSI: ORG. JEDINICA (0,N) - ZAHTEV (1,1) + UVRSTEN U: ZAHTEV (0,1) - PLAN (0,N)',
  [C('BROJ_ZAHTEVA', ID, False, 'PK - BROJ ZAHTEVA'),
   C('SIFRA_JEDINICE', ID, False, 'FK - veza PODNOSI'),
   C('SIFRA_PLANA', ID, True, 'FK - veza UVRSTEN U'),
   C('DATUM_ZAHTEVA', D, True, 'DATUM ZAHTEVA'),
   C('VRSTA_NABAVKE', T30, True, 'VRSTA NABAVKE'),
   C('PREDMET_ZAHTEVA', TXT, True, 'PREDMET ZAHTEVA'),
   C('OBRAZLOZENJE', TXT, True, 'OBRAZLOZENJE'),
   C('STATUS_ZAHTEVA', T20, True, 'STATUS ZAHTEVA'),
   C('PRIORITET', T20, True, 'PRIORITET'),
   C('PROCENJENA_VREDNOST', NOV, True, 'PROCENJENA VREDNOST')],
  ['BROJ_ZAHTEVA'],
  [('FK_ZAHNAB_PODNOSI', ['SIFRA_JEDINICE'], 'ORGANIZACIONA_JEDINICA', ['SIFRA_JEDINICE']),
   ('FK_ZAHNAB_UVRSTEN_U', ['SIFRA_PLANA'], 'PLAN_NABAVKE', ['SIFRA_PLANA'])])

T('STAVKA_PLANA_NABAVKE',
  'slab entitet STAVKA PLANA NABAVKE; identifikujuca veza SADRZI STAVKE PLANA: PLAN (1,N) - STAVKA (1,1)',
  [C('SIFRA_PLANA', ID, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_STAVKE', RB, False, 'PK - parcijalni kljuc RB STAVKE'),
   C('OPIS_ARTIKLA', TXT, True, 'OPIS ARTIKLA'),
   C('KOLICINA', INT, True, 'KOLICINA'),
   C('JEDINICA_MERE', T20, True, 'JEDINICA MERE'),
   C('PROCENJENA_CENA', NOV, True, 'PROCENJENA CENA'),
   C('PLANIRANI_KVARTAL', T20, True, 'PLANIRANI KVARTAL')],
  ['SIFRA_PLANA', 'RB_STAVKE'],
  [('FK_STPLAN_PLAN', ['SIFRA_PLANA'], 'PLAN_NABAVKE', ['SIFRA_PLANA'])])

T('DOBAVLJAC', 'jak entitet DOBAVLJAC (nadtip)',
  [C('SIFRA_DOBAVLJACA', ID, False, 'PK - SIFRA DOBAVLJACA'),
   C('NAZIV_DOBAVLJACA', N, False, 'NAZIV DOBAVLJACA'),
   C('PIB', 'CHAR(9)', True, 'PIB'),
   C('MATICNI_BROJ', 'CHAR(8)', True, 'MATICNI BROJ'),
   C('ADRESA', T60, True, 'ADRESA'),
   C('OCENA_DOBAVLJACA', PROC, True, 'OCENA DOBAVLJACA - izvedeni atribut')],
  ['SIFRA_DOBAVLJACA'])

T('DOBAVLJAC_TV_SADRZAJA', 'podtip DOBAVLJAC -> DOBAVLJAC TV SADRZAJA',
  [C('SIFRA_DOBAVLJACA', ID, False, 'PK = FK ka DOBAVLJAC'),
   C('VRSTA_SADRZAJA', T30, True, 'VRSTA SADRZAJA'),
   C('KATALOG_PONUDE', TXT, True, 'KATALOG PONUDE')],
  ['SIFRA_DOBAVLJACA'],
  [('FK_DOBTVSAD_DOBAVLJAC', ['SIFRA_DOBAVLJACA'], 'DOBAVLJAC', ['SIFRA_DOBAVLJACA'])])

T('DOBAVLJAC_OPREME_I_MATERIJALA', 'podtip DOBAVLJAC -> DOBAVLJAC OPREME I MATERIJALA',
  [C('SIFRA_DOBAVLJACA', ID, False, 'PK = FK ka DOBAVLJAC'),
   C('ASORTIMAN', TXT, True, 'ASORTIMAN'),
   C('OVLASCENI_SERVIS', T20, True, 'OVLASCENI SERVIS')],
  ['SIFRA_DOBAVLJACA'],
  [('FK_DOBOPR_DOBAVLJAC', ['SIFRA_DOBAVLJACA'], 'DOBAVLJAC', ['SIFRA_DOBAVLJACA'])])

T('PONUDA_DOBAVLJACA',
  'jak entitet PONUDA DOBAVLJACA + veza DOSTAVIO: DOBAVLJAC (0,N) - PONUDA (1,1)',
  [C('BROJ_PONUDE', ID, False, 'PK - BROJ PONUDE'),
   C('SIFRA_DOBAVLJACA', ID, False, 'FK - veza DOSTAVIO'),
   C('DATUM_PRIJEMA', D, True, 'DATUM PRIJEMA'),
   C('VAZI_DO', D, True, 'VAZI DO'),
   C('UKUPNA_CENA', NOV, True, 'UKUPNA CENA'),
   C('ROK_ISPORUKE', D, True, 'ROK ISPORUKE'),
   C('USLOVI_PLACANJA', TXT, True, 'USLOVI PLACANJA'),
   C('STATUS_PONUDE', T20, True, 'STATUS PONUDE'),
   C('UKUPNO_BODOVA', PROC, True, 'UKUPNO BODOVA - izvedeni atribut')],
  ['BROJ_PONUDE'],
  [('FK_PONUDA_DOSTAVIO', ['SIFRA_DOBAVLJACA'], 'DOBAVLJAC', ['SIFRA_DOBAVLJACA'])])

T('PONUDJENA_STAVKA',
  'veza PONUDJENA: STAVKA PLANA NABAVKE (0,N) - PONUDA DOBAVLJACA (0,N), sa atributima veze',
  [C('SIFRA_PLANA', ID, False, 'PK/FK ka STAVKA_PLANA_NABAVKE'),
   C('RB_STAVKE', RB, False, 'PK/FK ka STAVKA_PLANA_NABAVKE'),
   C('BROJ_PONUDE', ID, False, 'PK/FK ka PONUDA_DOBAVLJACA'),
   C('PONUDJENA_CENA', NOV, True, 'atribut veze PONUDJENA CENA'),
   C('ROK_ZA_STAVKU', D, True, 'atribut veze ROK ZA STAVKU')],
  ['SIFRA_PLANA', 'RB_STAVKE', 'BROJ_PONUDE'],
  [('FK_PONSTAV_STPLAN', ['SIFRA_PLANA', 'RB_STAVKE'], 'STAVKA_PLANA_NABAVKE', ['SIFRA_PLANA', 'RB_STAVKE']),
   ('FK_PONSTAV_PONUDA', ['BROJ_PONUDE'], 'PONUDA_DOBAVLJACA', ['BROJ_PONUDE'])])

T('KRITERIJUM_VREDNOVANJA', 'jak entitet KRITERIJUM VREDNOVANJA',
  [C('SIFRA_KRITERIJUMA', ID, False, 'PK - SIFRA KRITERIJUMA'),
   C('NAZIV_KRITERIJUMA', N, False, 'NAZIV KRITERIJUMA'),
   C('NACIN_BODOVANJA', T60, True, 'NACIN BODOVANJA'),
   C('OPIS_KRITERIJUMA', TXT, True, 'OPIS KRITERIJUMA')],
  ['SIFRA_KRITERIJUMA'])

T('OCENA_PONUDE',
  'veza VREDNUJE SE: PONUDA DOBAVLJACA (1,N) - KRITERIJUM VREDNOVANJA (1,N), sa atributima veze',
  [C('BROJ_PONUDE', ID, False, 'PK/FK ka PONUDA_DOBAVLJACA'),
   C('SIFRA_KRITERIJUMA', ID, False, 'PK/FK ka KRITERIJUM_VREDNOVANJA'),
   C('BROJ_BODOVA', PROC, True, 'atribut veze BROJ BODOVA'),
   C('KOMENTAR_OCENE', TXT, True, 'atribut veze KOMENTAR OCENE')],
  ['BROJ_PONUDE', 'SIFRA_KRITERIJUMA'],
  [('FK_OCENA_PONUDA', ['BROJ_PONUDE'], 'PONUDA_DOBAVLJACA', ['BROJ_PONUDE']),
   ('FK_OCENA_KRITERIJUM', ['SIFRA_KRITERIJUMA'], 'KRITERIJUM_VREDNOVANJA', ['SIFRA_KRITERIJUMA'])])

T('NARUDZBENICA',
  'jak entitet NARUDZBENICA + veza NARUCENO OD: DOBAVLJAC (0,N) - NARUDZBENICA (1,1)',
  [C('BROJ_NARUDZBENICE', ID, False, 'PK - BROJ NARUDZBENICE'),
   C('SIFRA_DOBAVLJACA', ID, False, 'FK - veza NARUCENO OD'),
   C('DATUM_IZDAVANJA', D, True, 'DATUM IZDAVANJA'),
   C('ROK_ISPORUKE', D, True, 'ROK ISPORUKE'),
   C('MESTO_ISPORUKE', T60, True, 'MESTO ISPORUKE'),
   C('UKUPAN_IZNOS', NOV, True, 'UKUPAN IZNOS - izvedeni atribut'),
   C('STATUS_NARUDZBINE', T20, True, 'STATUS NARUDZBINE')],
  ['BROJ_NARUDZBENICE'],
  [('FK_NARUDZB_NARUCENO_OD', ['SIFRA_DOBAVLJACA'], 'DOBAVLJAC', ['SIFRA_DOBAVLJACA'])])

T('STAVKA_NARUDZBENICE',
  'slab entitet STAVKA NARUDZBENICE; identifikujuca veza SADRZI STAVKE NARUDZBINE: NARUDZBENICA (1,N) - STAVKA (1,1)',
  [C('BROJ_NARUDZBENICE', ID, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_STAVKE', RB, False, 'PK - parcijalni kljuc RB STAVKE'),
   C('NAZIV_ARTIKLA', N, True, 'NAZIV ARTIKLA'),
   C('KOLICINA', INT, True, 'KOLICINA'),
   C('JEDINICNA_CENA', NOV, True, 'JEDINICNA CENA'),
   C('STATUS_STAVKE', T20, True, 'STATUS STAVKE'),
   C('VREDNOST_STAVKE', NOV, True, 'VREDNOST STAVKE - izvedeni atribut')],
  ['BROJ_NARUDZBENICE', 'RB_STAVKE'],
  [('FK_STNARUD_NARUDZBENICA', ['BROJ_NARUDZBENICE'], 'NARUDZBENICA', ['BROJ_NARUDZBENICE'])])

T('PRIJEMNICA',
  'jak entitet PRIJEMNICA + PRACENA: NARUDZBENICA (0,N) - PRIJEMNICA (1,1) + FAKTURISANA: PRIJEMNICA (0,1) - FAKTURA (0,N)',
  [C('BROJ_PRIJEMNICE', ID, False, 'PK - BROJ PRIJEMNICE'),
   C('BROJ_NARUDZBENICE', ID, False, 'FK - veza PRACENA'),
   C('BROJ_FAKTURE', ID, True, 'FK - veza FAKTURISANA'),
   C('DATUM_PRIJEMA', D, True, 'DATUM PRIJEMA'),
   C('BROJ_OTPREMNICE', T30, True, 'BROJ OTPREMNICE'),
   C('PRIMIO_MAGACIONER', T60, True, 'PRIMIO (MAGACIONER)'),
   C('ISPRAVNOST_ISPORUKE', T20, True, 'ISPRAVNOST ISPORUKE'),
   C('NAPOMENA', TXT, True, 'NAPOMENA')],
  ['BROJ_PRIJEMNICE'],
  [('FK_PRIJEMN_PRACENA', ['BROJ_NARUDZBENICE'], 'NARUDZBENICA', ['BROJ_NARUDZBENICE']),
   ('FK_PRIJEMN_FAKTURISANA', ['BROJ_FAKTURE'], 'FAKTURA', ['BROJ_FAKTURE'])])

T('PRIJEM_STAVKE',
  'veza PRIMLJENO PO: PRIJEMNICA (1,N) - STAVKA NARUDZBENICE (0,N), sa atributima veze',
  [C('BROJ_PRIJEMNICE', ID, False, 'PK/FK ka PRIJEMNICA'),
   C('BROJ_NARUDZBENICE', ID, False, 'PK/FK ka STAVKA_NARUDZBENICE'),
   C('RB_STAVKE', RB, False, 'PK/FK ka STAVKA_NARUDZBENICE'),
   C('PRIMLJENA_KOLICINA', INT, True, 'atribut veze PRIMLJENA KOLICINA'),
   C('UTVRDJENO_ODSTUPANJE', TXT, True, 'atribut veze UTVRDJENO ODSTUPANJE')],
  ['BROJ_PRIJEMNICE', 'BROJ_NARUDZBENICE', 'RB_STAVKE'],
  [('FK_PRIJSTAV_PRIJEMNICA', ['BROJ_PRIJEMNICE'], 'PRIJEMNICA', ['BROJ_PRIJEMNICE']),
   ('FK_PRIJSTAV_STNARUD', ['BROJ_NARUDZBENICE', 'RB_STAVKE'], 'STAVKA_NARUDZBENICE', ['BROJ_NARUDZBENICE', 'RB_STAVKE'])])

T('REKLAMACIJA',
  'jak entitet REKLAMACIJA + veza REKLAMIRANA: PRIJEMNICA (0,N) - REKLAMACIJA (1,1)',
  [C('BROJ_REKLAMACIJE', ID, False, 'PK - BROJ REKLAMACIJE'),
   C('BROJ_PRIJEMNICE', ID, False, 'FK - veza REKLAMIRANA'),
   C('DATUM_REKLAMACIJE', D, True, 'DATUM REKLAMACIJE'),
   C('RAZLOG_REKLAMACIJE', T60, True, 'RAZLOG REKLAMACIJE'),
   C('OPIS_NEDOSTATKA', TXT, True, 'OPIS NEDOSTATKA'),
   C('STATUS_REKLAMACIJE', T20, True, 'STATUS REKLAMACIJE'),
   C('DATUM_RESENJA', D, True, 'DATUM RESENJA'),
   C('REKLAMIRANI_IZNOS', NOV, True, 'REKLAMIRANI IZNOS'),
   C('NACIN_RESAVANJA', T60, True, 'NACIN RESAVANJA')],
  ['BROJ_REKLAMACIJE'],
  [('FK_REKLAMAC_PRIJEMNICA', ['BROJ_PRIJEMNICE'], 'PRIJEMNICA', ['BROJ_PRIJEMNICE'])])

T('REKLAMIRANA_STAVKA',
  'veza ODNOSI SE NA: REKLAMACIJA (1,N) - STAVKA NARUDZBENICE (0,N)',
  [C('BROJ_REKLAMACIJE', ID, False, 'PK/FK ka REKLAMACIJA'),
   C('BROJ_NARUDZBENICE', ID, False, 'PK/FK ka STAVKA_NARUDZBENICE'),
   C('RB_STAVKE', RB, False, 'PK/FK ka STAVKA_NARUDZBENICE')],
  ['BROJ_REKLAMACIJE', 'BROJ_NARUDZBENICE', 'RB_STAVKE'],
  [('FK_REKSTAV_REKLAMACIJA', ['BROJ_REKLAMACIJE'], 'REKLAMACIJA', ['BROJ_REKLAMACIJE']),
   ('FK_REKSTAV_STNARUD', ['BROJ_NARUDZBENICE', 'RB_STAVKE'], 'STAVKA_NARUDZBENICE', ['BROJ_NARUDZBENICE', 'RB_STAVKE'])])

# =====================================================================
# 7. FINANSIJE
# =====================================================================
T('FAKTURA',
  'jak entitet FAKTURA + veza IZDATA PO: UGOVOR (0,N) - FAKTURA (0,1)',
  [C('BROJ_FAKTURE', ID, False, 'PK - BROJ FAKTURE'),
   C('BROJ_UGOVORA', ID, True, 'FK - veza IZDATA PO'),
   C('DATUM_IZDAVANJA', D, True, 'DATUM IZDAVANJA'),
   C('ROK_PLACANJA', D, True, 'ROK PLACANJA'),
   C('SMER', T20, True, 'SMER (ULAZNA/IZLAZNA)'),
   C('OSNOVICA', NOV, True, 'OSNOVICA - izvedeni atribut'),
   C('IZNOS_PDV', NOV, True, 'IZNOS PDV - izvedeni atribut'),
   C('STATUS_PLACANJA', T20, True, 'STATUS PLACANJA'),
   C('IZNOS_ZA_PLACANJE', NOV, True, 'IZNOS ZA PLACANJE - izvedeni atribut')],
  ['BROJ_FAKTURE'],
  [('FK_FAKTURA_IZDATA_PO', ['BROJ_UGOVORA'], 'UGOVOR', ['BROJ_UGOVORA'])])

T('STAVKA_FAKTURE',
  'slab entitet STAVKA FAKTURE; identifikujuca veza SADRZI STAVKE FAKTURE: FAKTURA (1,N) - STAVKA (1,1)',
  [C('BROJ_FAKTURE', ID, False, 'PK/FK - identifikujuci vlasnik'),
   C('RB_STAVKE', RB, False, 'PK - parcijalni kljuc RB STAVKE'),
   C('OPIS_STAVKE', TXT, True, 'OPIS STAVKE'),
   C('KOLICINA', INT, True, 'KOLICINA'),
   C('JEDINICNA_CENA', NOV, True, 'JEDINICNA CENA'),
   C('STOPA_PDV', PROC, True, 'STOPA PDV'),
   C('VREDNOST_STAVKE', NOV, True, 'VREDNOST STAVKE - izvedeni atribut')],
  ['BROJ_FAKTURE', 'RB_STAVKE'],
  [('FK_STFAKT_FAKTURA', ['BROJ_FAKTURE'], 'FAKTURA', ['BROJ_FAKTURE'])])

T('NALOG_ZA_PLACANJE',
  'jak entitet NALOG ZA PLACANJE + veza PLACENA: FAKTURA (0,N) - NALOG (1,1)',
  [C('BROJ_NALOGA', ID, False, 'PK - BROJ NALOGA'),
   C('BROJ_FAKTURE', ID, False, 'FK - veza PLACENA'),
   C('DATUM_NALOGA', D, True, 'DATUM NALOGA'),
   C('IZNOS_NALOGA', NOV, True, 'IZNOS NALOGA'),
   C('SVRHA_PLACANJA', TXT, True, 'SVRHA PLACANJA'),
   C('DATUM_REALIZACIJE', D, True, 'DATUM REALIZACIJE'),
   C('STATUS_NALOGA', T20, True, 'STATUS NALOGA'),
   C('RACUN_PRIMAOCA', T30, True, 'RACUN PRIMAOCA'),
   C('ODOBRIO', T60, True, 'ODOBRIO')],
  ['BROJ_NALOGA'],
  [('FK_NALOG_PLACENA', ['BROJ_FAKTURE'], 'FAKTURA', ['BROJ_FAKTURE'])])
